![Kayak](https://seekvectorlogo.com/wp-content/uploads/2018/01/kayak-vector-logo.png)

# Plan your trip with Kayak 

## Company's description 📇

<a href="https://www.kayak.com" target="_blank">Kayak</a> is a travel search engine that helps user plan their next trip at the best price.

The company was founded in 2004 by Steve Hafner & Paul M. English. After a few rounds of fundraising, Kayak was acquired by <a href="https://www.bookingholdings.com/" target="_blank">Booking Holdings</a> which now holds: 

* <a href="https://booking.com/" target="_blank">Booking.com</a>
* <a href="https://kayak.com/" target="_blank">Kayak</a>
* <a href="https://www.priceline.com/" target="_blank">Priceline</a>
* <a href="https://www.agoda.com/" target="_blank">Agoda</a>
* <a href="https://Rentalcars.com/" target="_blank">RentalCars</a>
* <a href="https://www.opentable.com/" target="_blank">OpenTable</a>

With over \$300 million revenue a year, Kayak operates in almost all countries and all languages to help their users book travels accros the globe.

## Project 🚧

The marketing team needs help on a new project. After doing some user research, the team discovered that **70% of their users who are planning a trip would like to have more information about the destination they are going to**. 

In addition, user research shows that **people tend to be defiant about the information they are reading if they don't know the brand** which produced the content. 

Therefore, Kayak Marketing Team would like to create an application that will recommend where people should plan their next holidays. The application should be based on real data about:

* Weather 
* Hotels in the area 

The application should then be able to recommend the best destinations and hotels based on the above variables at any given time.

## Goals 🎯

As the project has just started, your team doesn't have any data that can be used to create this application. Therefore, your job will be to: 

* Scrape data from destinations 
* Get weather data from each destination 
* Get hotels' info about each destination
* Store all the information above in a data lake
* Extract, transform and load cleaned data from your datalake to a data warehouse

## Scope of this project 🖼️

Marketing team wants to focus first on the best cities to travel to in France. According <a href="https://one-week-in.com/35-cities-to-visit-in-france/" target="_blank">One Week In.com</a> here are the top-35 cities to visit in France: 

```python 
["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]
```

Your team should focus **only on the above cities for your project**.

## Helpers 🦮

To help you achieve this project, here are a few tips that should help you

### Get weather data with an API 

*   Use https://nominatim.org/ to get the gps coordinates of all the cities (no subscription required) Documentation : https://nominatim.org/release-docs/develop/api/Search/

*   Use https://openweathermap.org/appid (you have to subscribe to get a free apikey) and https://openweathermap.org/api/one-call-api to get some information about the weather for the 35 cities and put it in a DataFrame

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like 😎 Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later 😉 You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

### Scrape Booking.com 

Since BookingHoldings doesn't have aggregated databases, it will be much faster to scrape data directly from booking.com 

You can scrap as many information asyou want, but we suggest that you get at least:

*   hotel name,
*   Url to its booking.com page,
*   Its coordinates: latitude and longitude
*   Score given by the website users
*   Text description of the hotel


### Create your data lake using S3 

Once you managed to build your dataset, you should store into S3 as a csv file. 

### ETL 

Once you uploaded your data onto S3, it will be better for the next data analysis team to extract clean data directly from a Data Warehouse. Therefore, create a SQL Database using AWS RDS, extract your data from S3 and store it in your newly created DB.

## Deliverable 📬

To complete this project, your team should deliver:

* A `.csv` file in an S3 bucket containing enriched information about weather and hotels for each french city

* A SQL Database where we should be able to get the same cleaned data from S3 

* Two maps where you should have a Top-5 destinations and a Top-20 hotels in the area. You can use plotly or any other library to do so. It should look something like this: 

![Map](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Kayak_best_destination_project.png)

# 1. Get weather data with an API 
## 1.1 : get the coordinates of the cities :

*   Use https://nominatim.org/ to get the gps coordinates of all the cities (no subscription required) Documentation : https://nominatim.org/release-docs/develop/api/Search/

*   Use https://openweathermap.org/appid (you have to subscribe to get a free apikey) and https://openweathermap.org/api/one-call-api to get some information about the weather for the 35 cities and put it in a DataFrame

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like 😎 Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later 😉 You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

In [88]:
del AWS_BUCKET_DIR

In [1]:
import json
from dotenv import load_dotenv
import os
from networkx import add_path
import requests
import pandas as pd
import warnings
import logging  # for logging debug messages
import json
import random
import time

from django.conf.locale import de


# activate debug messages 
logger = logging.getLogger(__name__)

config_cities_list = ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

# parameters setting 

load_dotenv()
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY= os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_BUCKET_NAME = os.getenv("AWS_BUCKET_NAME")
AWS_BUCKET_DIR = os.getenv("AWS_BUCKET_DIR")
AWS_DB_NAME = os.getenv("AWS_DB_NAME")
AWS_DB_USER = os.getenv("AWS_DB_USER")
AWS_DB_PASS = os.getenv("AWS_DB_PASS")
AWS_REGION = os.getenv("AWS_REGION")
RDSHOST = os.getenv("RDSHOST")

BASE_URL_NOMINATIM = "https://nominatim.openstreetmap.org/search"
BASE_URL_OPENWEATHERMAP="https://api.openweathermap.org/data/2.5"

CONFIG_CITIES_FILE = "cities.csv"
MAX_CITIES_NUMBER = 35

from pathlib import Path

# Méthode simple : le CWD au lancement du kernel
# (généralement le dossier où se trouve le .ipynb, sauf si Jupyter a été lancé ailleurs)
notebook_dir = Path.cwd()
print(notebook_dir)

c:\Users\Cyril\Documents\python\jedha\jedha_Full_stack\Jedha_certif_CDSD\Block1\Kayak_weather_hotels\src

In [3]:
%whos

Variable                  Type           Data/Info
--------------------------------------------------
AWS_ACCESS_KEY            str            AKIA5Q4LO2TJDK4TYAHI
AWS_BUCKET_DIR            str            kayak
AWS_BUCKET_NAME           str            kayak-cyril
AWS_DB_NAME               str            kayak-db-cyril
AWS_DB_PASS               str            Siril12_kayak
AWS_DB_USER               str            postgres_kayak
AWS_REGION                str            eu-west-3
AWS_SECRET_ACCESS_KEY     str            /Tqy2dBbI6BfriCFwyEVlgr11Vxm91z5AsN9XR8B
BASE_DIR                  WindowsPath    c:\Users\Cyril\Documents\<...>ock1\Kayak_weather_hotels
BASE_URL_NOMINATIM        str            https://nominatim.openstreetmap.org/search
BASE_URL_OPENWEATHERMAP   str            https://api.openweathermap.org/data/2.5
CONFIG_CITIES_FILE        str            cities.csv
DATA_DIR                  WindowsPath    c:\Users\Cyril\Documents\<...>Kayak_weather_hotels\data
DATA_DIR_CONFIG           str            c:\Users\Cyril\Documents\<...>eather_hotels\data/config
DATA_DIR_CSV              str            c:\Users\Cyril\Documents\<...>k_weather_hotels\data/csv
DATA_DIR_HTML             str            c:\Users\Cyril\Documents\<...>_weather_hotels\data/html
DATA_DIR_JSON             str            c:\Users\Cyril\Documents\<...>_weather_hotels\data/json
DATA_DIR_JSON_CITIES      str            c:\Users\Cyril\Documents\<...>r_hotels\data/json/cities
DATA_DIR_JSON_HOTELS      str            c:\Users\Cyril\Documents\<...>r_hotels\data/json/hotels
DEFAULT_PARAMS            dict           n=1
HEADERS                   dict           n=1
MAX_CITIES_NUMBER         int            35
Path                      type           <class 'pathlib.Path'>
RDSHOST                   str            kayak-db-cyril.c96g6864en<...>-west-3.rds.amazonaws.com
SRC_DIR                   WindowsPath    c:\Users\Cyril\Documents\<...>\Kayak_weather_hotels\src
USER_AGENT                str            Mozilla/5.0 (X11; Linux x<...>e/124.0.0.0 Safari/537.36
VALID_TYPES               set            {'city', 'islet', 'histor<...>unty', 'gorge', 'hamlet'}
WEATHER_API_KEY           str            e6c25cd16e57edea5d19d272bf7c6a91
add_path                  function       <function add_path at 0x0000018825869260>
config_cities_list        list           n=35
de                        module         <module 'django.conf.loca<...>locale\\de\\__init__.py'>
json                      module         <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
load_dotenv               function       <function load_dotenv at 0x000001882577A3E0>
logger                    Logger         <Logger __main__ (WARNING)>
logging                   module         <module 'logging' from 'C<...>b\\logging\\__init__.py'>
notebook_dir              WindowsPath    c:\Users\Cyril\Documents\<...>\Kayak_weather_hotels\src
os                        module         <module 'os' (frozen)>
pd                        module         <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
random                    module         <module 'random' from 'C:<...>thon311\\Lib\\random.py'>
requests                  module         <module 'requests' from '<...>\\requests\\__init__.py'>
time                      module         <module 'time' (built-in)>
warnings                  module         <module 'warnings' from '<...>on311\\Lib\\warnings.py'>

In [2]:


os.chdir("..")
# add_path("./src")
BASE_DIR = Path.cwd()
print(f"base_dir : {BASE_DIR}")

#BASE_DIR = Path(__file__).resolve().parent
SRC_DIR = BASE_DIR / "src"

DATA_DIR = BASE_DIR / "data"
DATA_DIR_CONFIG = f"{DATA_DIR}/config"
os.makedirs(DATA_DIR_CONFIG, exist_ok=True)

DATA_DIR_CSV = f"{DATA_DIR}/csv"
os.makedirs(DATA_DIR_CSV, exist_ok=True)

DATA_DIR_HTML = f"{DATA_DIR}/html"
os.makedirs(DATA_DIR_HTML, exist_ok=True)

DATA_DIR_JSON = f"{DATA_DIR}/json"
os.makedirs(DATA_DIR_JSON, exist_ok=True)

DATA_DIR_JSON_CITIES = f"{DATA_DIR_JSON}/cities"
os.makedirs(DATA_DIR_JSON_CITIES, exist_ok=True)

DATA_DIR_JSON_HOTELS = f"{DATA_DIR_JSON}/hotels"
os.makedirs(DATA_DIR_JSON_HOTELS, exist_ok=True)

VALID_TYPES = {"city", "town", "village", "hamlet", "municipality", "islet", "historic", "tourism", "county", "gorge"}

USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

HEADERS = {'User-Agent': USER_AGENT}
DEFAULT_PARAMS = {"format": "json"}

# save first cities list to .csv (uncomment to save your first file !): 
# cities_list_df = pd.DataFrame({'city_name':config_cities_list})
# cities_list_df.to_csv (f"{DATA_DIR_CONFIG}/cities.csv",index=False, header=False)

base_dir : c:\Users\Cyril\Documents\python\jedha\jedha_Full_stack\Jedha_certif_CDSD\Block1\Kayak_weather_hotels

In [5]:
import sys
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))  # insert(0, ...) : priorité sur les autres chemins

In [ ]:
# #cities_list_df = pd.DataFrame(cities_list)
# cities_list_df = pd.DataFrame({'city_name':config_cities_list})
# cities_list_df.to_csv (f"{DATA_DIR_CONFIG}/cities.csv",index=False, header=False)

In [ ]:
# cities_list_df2 = pd.read_csv(f"{DATA_DIR_CONFIG}/cities.csv",header=None, names = ['city_name'])
# display(cities_list_df2)
# #

In [ ]:
#weather_api_key

In [4]:

# search gps coordinates for the 35 cities : 



def load_cities()-> pd.DataFrame :
    """load cities from a file or directly inside the function
    with column ['city_name']
    35 bst cities to visit in France
    """
    
    cities_list = pd.read_csv(f"{DATA_DIR_CONFIG}/{CONFIG_CITIES_FILE}",
                              header=None, names = ['city_name'])
    cities_list['city_name_plus'] = (
    cities_list["city_name"]
    .str.replace("'", "+", regex=False)
    .str.replace(" ", "+", regex=False)
    .str.replace("_", "+", regex=False)
    )
    
    cities_list['city_name_'] = (
        cities_list["city_name_plus"]
        .str.replace("+", "_", regex=False)
    )
    
    # add warning if more than 35 cities
    if len(cities_list)>MAX_CITIES_NUMBER:
        msg = f"More than {MAX_CITIES_NUMBER} in cities file from {DATA_DIR_CONFIG}/{CONFIG_CITIES_FILE}"
        warnings.warn(msg, UserWarning, stacklevel=2)
    return cities_list

def clean_name(name):
    """ clean name of city for name of file saving and city_id string
    replace "+" "'" & space by "_" 
    """
    name = name.replace(" ","_")
    name = name.replace("'",'_')
    name = name.replace('+','_')
    return name
    

def plus_name(name):
    """ plus name of city for search & query activities
    replace "_" "'" & space by "+" 
    """
    name = name.replace("'",'+')
    name = name.replace(" ","+")
    name = name.replace('_','+')
    return name

def _get_city_properties(data: list) -> dict | None:
    """get proper item in data from big json delivered by nominatim
    to extract later lat + lon properties  """
    for item in data:
        if item.get("addresstype") in VALID_TYPES:
            return item
    return None

def save_to_cache(city_name_: str, data):
    filename = f"{city_name_}.json"
    p = os.path.join(DATA_DIR_JSON_CITIES, filename)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)



def _cache_lookup(city_name_: str):
    """Return path of existing cache file for city_name_, or None."""
    p = os.path.join(DATA_DIR_JSON_CITIES, f"{city_name_}.json")
    return p if os.path.exists(p) else None


def load_from_cache(city_name_: str):
    """Load city data from json file if exists in cache dir."""
    
    data = _cache_lookup(city_name_)
    if data:
        with open(data, "r", encoding="utf-8") as f:
            try:
                return json.load(f)
            except Exception:
                return None
    return None

def clean_cities_names(cities_list):
    cleaned_cities_list = []
    for city in cities_list:
        city_enc =city.replace(' ','+')
        cleaned_cities_list.append(city_enc)
    return cleaned_cities_list

def extract_coordinates(data, feature_index=0):
    """Extrait les coordonnées [lon, lat] d'une feature GeoJSON."""
    try:
        coords = data["features"][feature_index]["geometry"]["coordinates"]
        lon, lat = coords[0], coords[1]
        return lon, lat
    except (KeyError, IndexError, TypeError) as e:
        raise ValueError(f"Impossible d'extraire les coordonnées: {e}")

# # Depuis un fichier
# with open("data.json", "r", encoding="utf-8") as f:
#     data = json.load(f)

# lon, lat = extract_coordinates(data, feature_index=0)
# print(f"Longitude: {lon}, Latitude: {lat}")

# Bonus : extraire toutes les features avec leur nom
def extract_all_coordinates(data):
    """Retourne une liste de (nom, lon, lat) pour toutes les features."""
    results = []
    for feat in data.get("features", []):
        try:
            name = feat["properties"].get("name", "N/A")
            lon, lat = feat["geometry"]["coordinates"]
            results.append((name, lon, lat))
        except (KeyError, TypeError):
            continue
    return results

def get_nominatim(city_cleaned:str, delay:int = 1.82, max_retries: int = 3, timeout: int = 10):
    """ get city coordinates from nominatim api 
    city_cleaned : str : spaces replaced by '+' 
    delay : delay from request order , default is 1.82 s 
    """

    params = DEFAULT_PARAMS.copy()
    params['q'] = city_cleaned
    params['countrycodes'] = 'fr'
    for attempt in range(max_retries):
        try:
            
            response = requests.get(
                url = BASE_URL_NOMINATIM, 
                headers = HEADERS,
                params = params, 
                timeout=10            
                )
        except (requests.exceptions.Timeout, 
                requests.exceptions.CorrectionError) as e:
            if attempt < max_retries - 1:
                time.sleep(wait)
                continue
            print(f"[get_nominatim] échec après {max_retries} tentatives ({city_cleaned!r}) : {e}")
            return None
        status = response.status_code
    
        if status == 200:
            try:
                data = response.json()
            except ValueError:
                data = None
            time.sleep(delay)
            
            return data or None
            
        if status == 429 or status >= 500:
            wait = delay *2 + random.uniform(0,0.52) 
            if attempt < max_retries -1:
                time.sleep(wait)
                continue
            return None
    
        # others codes (400, 403) : no retry , error is definitive
        return None
    return None

In [5]:

"""
Génération d'un identifiant stable et déterministe par ville, à utiliser
comme clé primaire/étrangère en base de données.
"""

import re
import unicodedata
import uuid
from typing import Optional


def slugify(text: str) -> str:
    """Convertit un texte en slug ASCII minuscule : accents retirés,
    espaces/apostrophes remplacés par '-', caractères non alphanumériques
    supprimés. Ex. "Saint-Étienne" -> "saint-etienne"."""
    if not text:
        return ""
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def city_id(city_name: str, latitude: Optional[float] = None, longitude: Optional[float] = None) -> str:
    """
    ID stable et lisible pour une ville — RECOMMANDÉ pour ton cas (liste
    restreinte de villes avec coordonnées déjà disponibles dans top_cities).

    - Sans coordonnées : city_id("Collioure") -> "collioure"
      Suffisant si tu es sûr qu'il n'y a pas d'homonymes dans ta liste.
    - Avec coordonnées (recommandé) : désambiguïse automatiquement les
      homonymes (ex. plusieurs "Saint-Martin" en France) sans registre
      externe à maintenir.
      city_id("Saint-Martin", 42.52, 3.08) -> "saint-martin-4252-0308"

    Déterministe : le même nom + mêmes coordonnées (arrondies à 2 décimales,
    soit ~1 km de précision) redonnent toujours le même ID d'un run à l'autre
    -> permet un upsert propre en base plutôt que des doublons.
    """
    base = slugify(city_name)
    if latitude is None or longitude is None:
        return base
    lat_part = f"{latitude:.2f}".replace(".", "").replace("-", "m")
    lon_part = f"{longitude:.2f}".replace(".", "").replace("-", "m")
    return f"{base}-{lat_part}-{lon_part}"


# --- Bonus : alternative en UUID opaque (déterministe aussi) ---------------
# Utile si ta base impose des clés UUID plutôt que des chaînes lisibles.
_CITY_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, "booking-scraper.cities")


def city_uuid(city_name: str) -> str:
    """UUID déterministe basé sur le nom normalisé (sans accents/casse).
    Même ville -> même UUID à chaque exécution, sans dépendre de coordonnées."""
    normalized = slugify(city_name)
    return str(uuid.uuid5(_CITY_NAMESPACE, normalized))


# if __name__ == "__main__":
#     # Exemple d'application à un DataFrame top_cities (colonnes: city, lat, lon)
#     import pandas as pd

#     top_cities = pd.DataFrame({
#         "city": ["Lyon", "Annecy", "Collioure"],
#         "lat": [45.7578137, 45.8992348, 42.52505],
#         "lon": [4.8320114, 6.1288847, 3.0831554],
#     })
#     top_cities["city_id"] = top_cities.apply(
#         lambda r: city_id(r["city"], r["lat"], r["lon"]), axis=1
#     )
#     print(top_cities)

In [6]:
    
# for name, lon, lat in extract_all_coordinates(data):
#     print(f"{name}: ({lon}, {lat})")

# ==============================================================
# *** main *** 
# ==============================================================
#gps_url = "https://nominatim.openstreetmap.org/search"

cities_list_df = load_cities()
cities_list_df

C:\Users\Cyril\AppData\Local\Temp\ipykernel_38280\3179138993.py:9: UserWarning: More than 35 in cities file from data/config/cities.csv
  cities_list_df = load_cities()

,city_name,city_name_plus,city_name_
0,Mont Saint Michel,Mont+Saint+Michel,Mont_Saint_Michel
1,St Malo,St+Malo,St_Malo
2,Bayeux,Bayeux,Bayeux
3,Le Havre,Le+Havre,Le_Havre
4,Rouen,Rouen,Rouen
5,Paris,Paris,Paris
6,Amiens,Amiens,Amiens
7,Lille,Lille,Lille
8,Strasbourg,Strasbourg,Strasbourg
9,Chateau du Haut Koenigsbourg,Chateau+du+Haut+Koenigsbourg,Chateau_du_Haut_Koenigsbourg
10,Colmar,Colmar,Colmar
11,Eguisheim,Eguisheim,Eguisheim
12,Besancon,Besancon,Besancon
13,Dijon,Dijon,Dijon
14,Annecy,Annecy,Annecy
15,Grenoble,Grenoble,Grenoble
16,Lyon,Lyon,Lyon
17,Gorges du Verdon,Gorges+du+Verdon,Gorges_du_Verdon
18,Bormes les Mimosas,Bormes+les+Mimosas,Bormes_les_Mimosas
19,Cassis,Cassis,Cassis
20,Marseille,Marseille,Marseille
21,Aix en Provence,Aix+en+Provence,Aix_en_Provence
22,Avignon,Avignon,Avignon
23,Uzes,Uzes,Uzes
24,Nimes,Nimes,Nimes
25,Aigues Mortes,Aigues+Mortes,Aigues_Mortes
26,Saintes Maries de la mer,Saintes+Maries+de+la+mer,Saintes_Maries_de_la_mer
27,Collioure,Collioure,Collioure
28,Carcassonne,Carcassonne,Carcassonne
29,Ariege,Ariege,Ariege
30,Toulouse,Toulouse,Toulouse
31,Montauban,Montauban,Montauban
32,Biarritz,Biarritz,Biarritz
33,Bayonne,Bayonne,Bayonne
34,La Rochelle,La+Rochelle,La_Rochelle
35,Issoudun,Issoudun,Issoudun
36,Voiron,Voiron,Voiron

In [7]:

# cleaned_cities = clean_cities_names(cities_list)
# print(cleaned_cities)
def get_coordinates_cities(cities_list_df) -> pd.DataFrame:
    """ get coordinates for all cities from dataframe to dataframe """
    results = []
    for idx,row in cities_list_df.iterrows():
        city = row['city_name']
        city_ = row['city_name_']
        city_plus = row['city_name_plus']
        
        # city = row['city_name']
        
        # city_plus = row['city_name_plus']
        # city_ = row['city_name_']
        
        #https://nominatim.openstreetmap.org/search?<params>
        #city_enc =city.replace(' ','+')
        # params = "?q="+city
        # format = "&format=geojson"
        # input_url = gps_url+params+format
        # print(input_url)
        #response = requests.get(input_url)
        
        # read from cache if city is already there 
        # if yes : take data from cache in same json format as direct call from nominatim: 
        data = load_from_cache(city_)
        if data is None:
        # else : get coordinates:
            data = get_nominatim(city_plus)
            
        if data:
            save_to_cache(city_,data)
            # print for debug
            logger.debug("%s coord : %s", city, data)   # <-- remplace print()
    
            # save data in cache :
            item = _get_city_properties(data)
            if item:
                results.append({
                    "city_name"  : city,
                    "city_name_" : city_,
                    "city_plus"  : city_plus,
                    "lat": item.get("lat"),
                    "lon": item.get("lon"),
                    
                })
            else:
                # item is None : 
                results.append({
                                    "city_name"  : city,
                                    "city_name_" : city_,
                                    "city_plus"  : city_plus,
                                    "lat": None,
                                    "lon": None
                            })
        else:
            # data is none : report error in reading coordinates 
            results.append({
                    "city_name"  : city,
                    "city_name_" : city_,
                    "city_plus"  : city_plus,
                    "lat": None,
                    "lon": None
            })
               
    results_df = pd.DataFrame(results)
    results_df["lat"] = pd.to_numeric(results_df["lat"], errors="coerce")
    results_df["lon"] = pd.to_numeric(results_df["lon"], errors="coerce")
    return results_df
   
        
    #print(response.json())      

results_df = get_coordinates_cities(cities_list_df)  
results_df

,city_name,city_name_,city_plus,lat,lon
0,Mont Saint Michel,Mont_Saint_Michel,Mont+Saint+Michel,48.635954,-1.511460
1,St Malo,St_Malo,St+Malo,48.649518,-2.026041
2,Bayeux,Bayeux,Bayeux,49.276462,-0.702474
3,Le Havre,Le_Havre,Le+Havre,49.493898,0.107973
4,Rouen,Rouen,Rouen,49.440459,1.093966
5,Paris,Paris,Paris,48.853495,2.348391
6,Amiens,Amiens,Amiens,49.894171,2.295695
7,Lille,Lille,Lille,50.636565,3.063528
8,Strasbourg,Strasbourg,Strasbourg,48.584614,7.750713
9,Chateau du Haut Koenigsbourg,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,48.249382,7.343941
10,Colmar,Colmar,Colmar,48.077752,7.357964
11,Eguisheim,Eguisheim,Eguisheim,48.044797,7.307962
12,Besancon,Besancon,Besancon,47.238022,6.024362
13,Dijon,Dijon,Dijon,47.321581,5.041470
14,Annecy,Annecy,Annecy,45.899235,6.128885
15,Grenoble,Grenoble,Grenoble,45.187560,5.735782
16,Lyon,Lyon,Lyon,45.757814,4.832011
17,Gorges du Verdon,Gorges_du_Verdon,Gorges+du+Verdon,43.749656,6.328562
18,Bormes les Mimosas,Bormes_les_Mimosas,Bormes+les+Mimosas,43.150697,6.341928
19,Cassis,Cassis,Cassis,43.214036,5.539632
20,Marseille,Marseille,Marseille,43.296399,5.377789
21,Aix en Provence,Aix_en_Provence,Aix+en+Provence,43.529842,5.447474
22,Avignon,Avignon,Avignon,43.949249,4.805901
23,Uzes,Uzes,Uzes,44.012128,4.419672
24,Nimes,Nimes,Nimes,43.837425,4.360069
25,Aigues Mortes,Aigues_Mortes,Aigues+Mortes,43.566152,4.191540
26,Saintes Maries de la mer,Saintes_Maries_de_la_mer,Saintes+Maries+de+la+mer,43.451592,4.427720
27,Collioure,Collioure,Collioure,42.525050,3.083155
28,Carcassonne,Carcassonne,Carcassonne,43.213036,2.349107
29,Ariege,Ariege,Ariege,42.945537,1.406554
30,Toulouse,Toulouse,Toulouse,43.604464,1.444243
31,Montauban,Montauban,Montauban,44.017584,1.354999
32,Biarritz,Biarritz,Biarritz,43.483252,-1.559278
33,Bayonne,Bayonne,Bayonne,43.494514,-1.473666
34,La Rochelle,La_Rochelle,La+Rochelle,46.159732,-1.151595
35,Issoudun,Issoudun,Issoudun,46.947766,1.988281
36,Voiron,Voiron,Voiron,45.363139,5.591075

In [8]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city_name   37 non-null     object
 1   city_name_  37 non-null     object
 2   city_plus   37 non-null     object
 3   lat         37 non-null     float64
 4   lon         37 non-null     float64
dtypes: float64(2), object(3)
memory usage: 1.6+ KB

In [9]:
results_df["city_id"] = results_df.apply(
        lambda r: city_id(r["city_name"], r["lat"], r["lon"]), axis=1)

results_df

,city_name,city_name_,city_plus,lat,lon,city_id
0,Mont Saint Michel,Mont_Saint_Michel,Mont+Saint+Michel,48.635954,-1.511460,mont-saint-michel-4864-m151
1,St Malo,St_Malo,St+Malo,48.649518,-2.026041,st-malo-4865-m203
2,Bayeux,Bayeux,Bayeux,49.276462,-0.702474,bayeux-4928-m070
3,Le Havre,Le_Havre,Le+Havre,49.493898,0.107973,le-havre-4949-011
4,Rouen,Rouen,Rouen,49.440459,1.093966,rouen-4944-109
5,Paris,Paris,Paris,48.853495,2.348391,paris-4885-235
6,Amiens,Amiens,Amiens,49.894171,2.295695,amiens-4989-230
7,Lille,Lille,Lille,50.636565,3.063528,lille-5064-306
8,Strasbourg,Strasbourg,Strasbourg,48.584614,7.750713,strasbourg-4858-775
9,Chateau du Haut Koenigsbourg,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,48.249382,7.343941,chateau-du-haut-koenigsbourg-4825-734
10,Colmar,Colmar,Colmar,48.077752,7.357964,colmar-4808-736
11,Eguisheim,Eguisheim,Eguisheim,48.044797,7.307962,eguisheim-4804-731
12,Besancon,Besancon,Besancon,47.238022,6.024362,besancon-4724-602
13,Dijon,Dijon,Dijon,47.321581,5.041470,dijon-4732-504
14,Annecy,Annecy,Annecy,45.899235,6.128885,annecy-4590-613
15,Grenoble,Grenoble,Grenoble,45.187560,5.735782,grenoble-4519-574
16,Lyon,Lyon,Lyon,45.757814,4.832011,lyon-4576-483
17,Gorges du Verdon,Gorges_du_Verdon,Gorges+du+Verdon,43.749656,6.328562,gorges-du-verdon-4375-633
18,Bormes les Mimosas,Bormes_les_Mimosas,Bormes+les+Mimosas,43.150697,6.341928,bormes-les-mimosas-4315-634
19,Cassis,Cassis,Cassis,43.214036,5.539632,cassis-4321-554
20,Marseille,Marseille,Marseille,43.296399,5.377789,marseille-4330-538
21,Aix en Provence,Aix_en_Provence,Aix+en+Provence,43.529842,5.447474,aix-en-provence-4353-545
22,Avignon,Avignon,Avignon,43.949249,4.805901,avignon-4395-481
23,Uzes,Uzes,Uzes,44.012128,4.419672,uzes-4401-442
24,Nimes,Nimes,Nimes,43.837425,4.360069,nimes-4384-436
25,Aigues Mortes,Aigues_Mortes,Aigues+Mortes,43.566152,4.191540,aigues-mortes-4357-419
26,Saintes Maries de la mer,Saintes_Maries_de_la_mer,Saintes+Maries+de+la+mer,43.451592,4.427720,saintes-maries-de-la-mer-4345-443
27,Collioure,Collioure,Collioure,42.525050,3.083155,collioure-4253-308
28,Carcassonne,Carcassonne,Carcassonne,43.213036,2.349107,carcassonne-4321-235
29,Ariege,Ariege,Ariege,42.945537,1.406554,ariege-4295-141
30,Toulouse,Toulouse,Toulouse,43.604464,1.444243,toulouse-4360-144
31,Montauban,Montauban,Montauban,44.017584,1.354999,montauban-4402-135
32,Biarritz,Biarritz,Biarritz,43.483252,-1.559278,biarritz-4348-m156
33,Bayonne,Bayonne,Bayonne,43.494514,-1.473666,bayonne-4349-m147
34,La Rochelle,La_Rochelle,La+Rochelle,46.159732,-1.151595,la-rochelle-4616-m115
35,Issoudun,Issoudun,Issoudun,46.947766,1.988281,issoudun-4695-199
36,Voiron,Voiron,Voiron,45.363139,5.591075,voiron-4536-559

In [10]:

#DATA_DIR_CSV = ./json
results_df.to_csv(os.path.join(DATA_DIR_CSV, "cities.csv"), index=False, encoding="utf-8")
print("Saved", len(results_df), "rows to", os.path.join(DATA_DIR_CSV, "cities.csv"))

Saved 37 rows to data/csv\cities.csv

## 1.2 : weather forecasts
*   Use https://openweathermap.org/appid (you have to subscribe to get a free apikey) and https://openweathermap.org/api/one-call-api to get some information about the weather for the 35 cities and put it in a DataFrame

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like 😎 Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later 😉 You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

In [11]:
results1=results_df.loc[1]

In [12]:
# get weather forecasts of all cities by calling the api 

# determine the top 7 cities with the best weather conditions for next 7 days
#  daily.pop and daily.rain : expected volume of rain in next days 
# temperature + humidity 

# API call 2.5 soon deprecated:
#https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude={part}&appid={API key}

# API call 4.0

# https://api.openweathermap.org/data/4.0/onecall/current?lat={lat}&lon={lon}&appid={API key}

#WEATHER_API_KEY = weather_api_key


# adds for tests
lat = results1['lat']
lon = results1['lon']
#https://api.openweathermap.org/data/2.5/onecall/current?lat=48.6495180&lon=-2.0260409&units=metric&lang=en&appid={'e6c25cd16e57edea5d19d272bf7c6a91'}



def get_weather(lat:float, lon:float) -> dict :
    """ get weatherforecast from openweathermap
    """
    params = {
        "lat": lat, "lon": lon,
        #"cnt": 100,
        "units": "metric",
        "appid": WEATHER_API_KEY,
    }
    response = requests.get(url=f"{BASE_URL_OPENWEATHERMAP}/forecast" ,
                            params = params,
                            timeout = 10)
    if response.status_code == 200:
        return response.json()
    print(f"  openweathermap error {response.status_code}: {response.text[:200]}")
    return None

def compile_weather(weather_data)-> pd.DataFrame:
    """ compile in a dataFrame weather data 
    coming from call weather_api
    that is in json format"""

    df_weather = pd.json_normalize(
        weather_data["list"],
        sep="_",
        record_path=["weather"],      # extrait weather (liste imbriquée) comme colonnes séparées
        meta=[
            "dt", "dt_txt", "visibility", "pop",
            ["main", "temp"], ["main", "feels_like"], ["main", "temp_min"], ["main", "temp_max"],
            ["main", "pressure"], ["main", "humidity"], ["main", "dew_point"],
            ["wind", "speed"], ["wind", "deg"], ["wind", "gust"],
            ["clouds", "all"], ["sys", "pod"],
        ],
        meta_prefix="",
        errors="ignore",              # tolère les champs absents (ex: pas de gust sur certaines entrées)
        record_prefix="weather_",
    )

    df_weather["datetime"] = pd.to_datetime(df_weather["dt_txt"])
    df_weather = df_weather.sort_values("datetime").reset_index(drop=True)
    return df_weather

In [13]:
pd.set_option("display.max_columns", None)   # affiche toutes les colonnes
pd.set_option("display.width", None)         # pas de troncature de largeur (auto-adapte au terminal/notebook)
pd.set_option("display.max_colwidth", None)  # pas de troncature du contenu des cellules
pd.set_option("display.max_rows", 100)       # optionnel : plus de lignes visibles (défaut 60)

In [14]:

def compile_weather2(data):
    df = pd.json_normalize(data["list"], sep="_")
    # df["weather_main"] = df["weather"].apply(lambda w: w[0]["main"] if w else None)
    # df["weather_description"] = df["weather"].apply(lambda w: w[0]["description"] if w else None)
    # df = df.drop(columns="weather")
    
    # 2eme iter : 
    # Extraction du champ weather (liste imbriquée avec 1 élément par entrée)
    weather_df = pd.json_normalize(df["weather"].apply(lambda w: w[0] if w else {}))
    weather_df = weather_df.add_prefix("weather_")

    df = pd.concat([df.drop(columns="weather"), weather_df], axis=1)
    df["datetime"] = pd.to_datetime(df["dt_txt"])
    df = df.sort_values("datetime").reset_index(drop=True)

        
    return df
   
   
weather_forecast = get_weather(lat,lon)    
print(weather_forecast)
df_weather2 = compile_weather2(weather_forecast)

display(df_weather2.head())

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1790326800, 'main': {'temp': 17.29, 'feels_like': 17.22, 'temp_min': 17.29, 'temp_max': 18.44, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1018, 'humidity': 82, 'temp_kf': -1.15, 'dew_point': 14.19}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 15}, 'wind': {'speed': 2.58, 'deg': 278, 'gust': 4.96}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-25 09:00:00'}, {'dt': 1790337600, 'main': {'temp': 18.14, 'feels_like': 18.12, 'temp_min': 18.14, 'temp_max': 19.84, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1018, 'humidity': 81, 'temp_kf': -1.7, 'dew_point': 14.83}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 23}, 'wind': {'speed': 5.05, 'deg': 306, 'gust': 8.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-25 12:00:00'}, {'dt': 1790348400, 'main': {'temp': 19.33, 'feels_like': 19.41, 'temp_min': 19.33, 'temp_max': 20.35, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1018, 'humidity': 80, 'temp_kf': -1.02, 'dew_point': 15.8}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 25}, 'wind': {'speed': 5.1, 'deg': 316, 'gust': 8.69}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-25 15:00:00'}, {'dt': 1790359200, 'main': {'temp': 16.61, 'feels_like': 16.55, 'temp_min': 16.61, 'temp_max': 16.61, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1019, 'humidity': 85, 'temp_kf': 0, 'dew_point': 14.83}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 54}, 'wind': {'speed': 6.2, 'deg': 321, 'gust': 9.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-25 18:00:00'}, {'dt': 1790370000, 'main': {'temp': 16.85, 'feels_like': 16.55, 'temp_min': 16.85, 'temp_max': 16.85, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1020, 'humidity': 75, 'temp_kf': 0, 'dew_point': 13.82}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 98}, 'wind': {'speed': 5.86, 'deg': 325, 'gust': 8.87}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-25 21:00:00'}, {'dt': 1790380800, 'main': {'temp': 16.46, 'feels_like': 16.2, 'temp_min': 16.46, 'temp_max': 16.46, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1020, 'humidity': 78, 'temp_kf': 0, 'dew_point': 14.01}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 6.32, 'deg': 340, 'gust': 9.64}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-26 00:00:00'}, {'dt': 1790391600, 'main': {'temp': 15.99, 'feels_like': 15.66, 'temp_min': 15.99, 'temp_max': 15.99, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1021, 'humidity': 77, 'temp_kf': 0, 'dew_point': 13.17}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 20}, 'wind': {'speed': 6.03, 'deg': 343, 'gust': 9.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-26 03:00:00'}, {'dt': 1790402400, 'main': {'temp': 15.28, 'feels_like': 14.82, 'temp_min': 15.28, 'temp_max': 15.28, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1022, 'humidity': 75, 'temp_kf': 0, 'dew_point': 12.41}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 52}, 'wind': {'speed': 4.87, 'deg': 356, 'gust': 7.55}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-26 06:00:00'}, {'dt': 1790413200, 'main': {'temp': 17.81, 'feels_like': 17.42, 'temp_min': 17.81, 'temp_max': 17.81, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1023, 'humidity': 68, 'temp_kf': 0, 'dew_point': 11.73}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.85, 'deg': 8, 'gust': 6.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-26 09:00:00'}, {'dt': 1790424000, 'main': {'temp': 19.45, 'feels_like': 19.1, 'temp_min': 19.45, 'temp_max': 19.45, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1022, 'humidity': 63, 'temp_kf': 0, 'dew_point': 10.88}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.09, 'deg': 14, 'gust': 6.06}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-26 12:00:00'}, {'dt': 1790434800, 'main': {'temp': 19.83, 'feels_like': 19.54, 'temp_min': 19.83, 'temp_max': 19.83, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1021, 'humidity': 64, 'temp_kf': 0, 'dew_point': 11.09}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.1, 'deg': 348, 'gust': 5.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-26 15:00:00'}, {'dt': 1790445600, 'main': {'temp': 16.56, 'feels_like': 16.05, 'temp_min': 16.56, 'temp_max': 16.56, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1020, 'humidity': 68, 'temp_kf': 0, 'dew_point': 11.79}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.48, 'deg': 6, 'gust': 5.53}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-26 18:00:00'}, {'dt': 1790456400, 'main': {'temp': 15.82, 'feels_like': 15.47, 'temp_min': 15.82, 'temp_max': 15.82, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1019, 'humidity': 77, 'temp_kf': 0, 'dew_point': 13.24}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 3}, 'wind': {'speed': 3.94, 'deg': 81, 'gust': 5.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-26 21:00:00'}, {'dt': 1790467200, 'main': {'temp': 15.03, 'feels_like': 14.81, 'temp_min': 15.03, 'temp_max': 15.03, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 85, 'temp_kf': 0, 'dew_point': 13.04}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 75}, 'wind': {'speed': 2.88, 'deg': 114, 'gust': 4.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-27 00:00:00'}, {'dt': 1790478000, 'main': {'temp': 15.44, 'feels_like': 15.36, 'temp_min': 15.44, 'temp_max': 15.44, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1014, 'humidity': 89, 'temp_kf': 0, 'dew_point': 13.46}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 91}, 'wind': {'speed': 2.86, 'deg': 143, 'gust': 4.68}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.43}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-27 03:00:00'}, {'dt': 1790488800, 'main': {'temp': 15.61, 'feels_like': 15.45, 'temp_min': 15.61, 'temp_max': 15.61, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1013, 'humidity': 85, 'temp_kf': 0, 'dew_point': 12.9}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 54}, 'wind': {'speed': 3.9, 'deg': 161, 'gust': 6.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-27 06:00:00'}, {'dt': 1790499600, 'main': {'temp': 19.11, 'feels_like': 18.8, 'temp_min': 19.11, 'temp_max': 19.11, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1013, 'humidity': 66, 'temp_kf': 0, 'dew_point': 12.52}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 92}, 'wind': {'speed': 3.63, 'deg': 189, 'gust': 6.39}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-27 09:00:00'}, {'dt': 1790510400, 'main': {'temp': 22.51, 'feels_like': 22.33, 'temp_min': 22.51, 'temp_max': 22.51, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1013, 'humidity': 58, 'temp_kf': 0, 'dew_point': 13.61}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 4.24, 'deg': 235, 'gust': 7.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-27 12:00:00'}, {'dt': 1790521200, 'main': {'temp': 19.52, 'feels_like': 19.75, 'temp_min': 19.52, 'temp_max': 19.52, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1012, 'humidity': 85, 'temp_kf': 0, 'dew_point': 16.78}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.95, 'deg': 222, 'gust': 3.29}, 'visibility': 3694, 'pop': 1, 'rain': {'3h': 4.5}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-27 15:00:00'}, {'dt': 1790532000, 'main': {'temp': 18.92, 'feels_like': 19.22, 'temp_min': 18.92, 'temp_max': 18.92, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1012, 'humidity': 90, 'temp_kf': 0, 'dew_point': 17.15}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 98}, 'wind': {'speed': 5.72, 'deg': 186, 'gust': 8.47}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.89}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-27 18:00:00'}, {'dt': 1790542800, 'main': {'temp': 18.73, 'feels_like': 19.09, 'temp_min': 18.73, 'temp_max': 18.73, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1013, 'humidity': 93, 'temp_kf': 0, 'dew_point': 17.33}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.25, 'deg': 211, 'gust': 7.81}, 'visibility': 8467, 'pop': 0.71, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-27 21:00:00'}, {'dt': 1790553600, 'main': {'temp': 17.67, 'feels_like': 17.89, 'temp_min': 17.67, 'temp_max': 17.67, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1014, 'humidity': 92, 'temp_kf': 0, 'dew_point': 16.25}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.85, 'deg': 299, 'gust': 7.96}, 'visibility': 3811, 'pop': 0.99, 'rain': {'3h': 2.61}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-28 00:00:00'}, {'dt': 1790564400, 'main': {'temp': 17.48, 'feels_like': 17.53, 'temp_min': 17.48, 'temp_max': 17.48, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1014, 'humidity': 86, 'temp_kf': 0, 'dew_point': 14.99}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.78, 'deg': 324, 'gust': 5.67}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 1.27}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-28 03:00:00'}, {'dt': 1790575200, 'main': {'temp': 17.02, 'feels_like': 17.05, 'temp_min': 17.02, 'temp_max': 17.02, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1016, 'humidity': 87, 'temp_kf': 0, 'dew_point': 14.66}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.08, 'deg': 349, 'gust': 4.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-28 06:00:00'}, {'dt': 1790586000, 'main': {'temp': 18.11, 'feels_like': 18.07, 'temp_min': 18.11, 'temp_max': 18.11, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1017, 'humidity': 80, 'temp_kf': 0, 'dew_point': 14.42}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.71, 'deg': 32, 'gust': 4.84}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-28 09:00:00'}, {'dt': 1790596800, 'main': {'temp': 19.09, 'feels_like': 19.01, 'temp_min': 19.09, 'temp_max': 19.09, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1017, 'humidity': 75, 'temp_kf': 0, 'dew_point': 14.38}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.94, 'deg': 64, 'gust': 6.86}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-28 12:00:00'}, {'dt': 1790607600, 'main': {'temp': 18.96, 'feels_like': 18.9, 'temp_min': 18.96, 'temp_max': 18.96, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1015, 'humidity': 76, 'temp_kf': 0, 'dew_point': 14.56}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.7, 'deg': 39, 'gust': 6.14}, 'visibility': 5559, 'pop': 0.78, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-28 15:00:00'}, {'dt': 1790618400, 'main': {'temp': 17.99, 'feels_like': 18.25, 'temp_min': 17.99, 'temp_max': 17.99, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1014, 'humidity': 92, 'temp_kf': 0, 'dew_point': 16.5}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.18, 'deg': 95, 'gust': 4.85}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 1.17}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-28 18:00:00'}, {'dt': 1790629200, 'main': {'temp': 17.22, 'feels_like': 17.4, 'temp_min': 17.22, 'temp_max': 17.22, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1013, 'humidity': 92, 'temp_kf': 0, 'dew_point': 15.7}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 4.69, 'deg': 112, 'gust': 7.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-28 21:00:00'}, {'dt': 1790640000, 'main': {'temp': 17.67, 'feels_like': 17.95, 'temp_min': 17.67, 'temp_max': 17.67, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1011, 'humidity': 94, 'temp_kf': 0, 'dew_point': 16.59}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 17}, 'wind': {'speed': 3.99, 'deg': 111, 'gust': 6.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-29 00:00:00'}, {'dt': 1790650800, 'main': {'temp': 17.62, 'feels_like': 17.89, 'temp_min': 17.62, 'temp_max': 17.62, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1009, 'humidity': 94, 'temp_kf': 0, 'dew_point': 16.52}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 69}, 'wind': {'speed': 5.22, 'deg': 151, 'gust': 8.03}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 1.41}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-29 03:00:00'}, {'dt': 1790661600, 'main': {'temp': 17.83, 'feels_like': 18.1, 'temp_min': 17.83, 'temp_max': 17.83, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 93, 'temp_kf': 0, 'dew_point': 16.55}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 96}, 'wind': {'speed': 5.99, 'deg': 163, 'gust': 9.24}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-29 06:00:00'}, {'dt': 1790672400, 'main': {'temp': 20.67, 'feels_like': 21.01, 'temp_min': 20.67, 'temp_max': 20.67, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1008, 'humidity': 85, 'temp_kf': 0, 'dew_point': 17.86}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 85}, 'wind': {'speed': 7.06, 'deg': 154, 'gust': 11.2}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-29 09:00:00'}, {'dt': 1790683200, 'main': {'temp': 24.18, 'feels_like': 24.46, 'temp_min': 24.18, 'temp_max': 24.18, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1007, 'humidity': 69, 'temp_kf': 0, 'dew_point': 18.08}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 95}, 'wind': {'speed': 8.04, 'deg': 168, 'gust': 12.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-29 12:00:00'}, {'dt': 1790694000, 'main': {'temp': 24.29, 'feels_like': 24.52, 'temp_min': 24.29, 'temp_max': 24.29, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1007, 'humidity': 67, 'temp_kf': 0, 'dew_point': 17.78}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 94}, 'wind': {'speed': 7.57, 'deg': 172, 'gust': 11.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-09-29 15:00:00'}, {'dt': 1790704800, 'main': {'temp': 22.66, 'feels_like': 22.89, 'temp_min': 22.66, 'temp_max': 22.66, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1007, 'humidity': 73, 'temp_kf': 0, 'dew_point': 17.54}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 99}, 'wind': {'speed': 6.67, 'deg': 177, 'gust': 10.09}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.18}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-29 18:00:00'}, {'dt': 1790715600, 'main': {'temp': 20.42, 'feels_like': 20.76, 'temp_min': 20.42, 'temp_max': 20.42, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1008, 'humidity': 86, 'temp_kf': 0, 'dew_point': 17.86}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 99}, 'wind': {'speed': 5.86, 'deg': 173, 'gust': 8.96}, 'visibility': 6784, 'pop': 0.93, 'rain': {'3h': 1.62}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-29 21:00:00'}, {'dt': 1790726400, 'main': {'temp': 19.41, 'feels_like': 19.73, 'temp_min': 19.41, 'temp_max': 19.41, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1009, 'humidity': 89, 'temp_kf': 0, 'dew_point': 17.34}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 94}, 'wind': {'speed': 6.94, 'deg': 179, 'gust': 10.56}, 'visibility': 10000, 'pop': 0.44, 'rain': {'3h': 0.93}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-30 00:00:00'}, {'dt': 1790737200, 'main': {'temp': 19.49, 'feels_like': 19.84, 'temp_min': 19.49, 'temp_max': 19.49, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1009, 'humidity': 90, 'temp_kf': 0, 'dew_point': 17.71}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 6}, 'wind': {'speed': 6, 'deg': 196, 'gust': 9.11}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.18}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-30 03:00:00'}, {'dt': 1790748000, 'main': {'temp': 18.11, 'feels_like': 18.4, 'temp_min': 18.11, 'temp_max': 18.11, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1011, 'humidity': 93, 'temp_kf': 0, 'dew_point': 16.73}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 2}, 'wind': {'speed': 5.06, 'deg': 203, 'gust': 7.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-09-30 06:00:00'}], 'city': {'id': 2978640, 'name': 'St-Malo', 'coord': {'lat': 48.6495, 'lon': -2.026}, 'country': 'FR', 'population': 50676, 'timezone': 7200, 'sunrise': 1790315913, 'sunset': 1790359268}}

,dt,visibility,pop,dt_txt,main_temp,main_feels_like,main_temp_min,main_temp_max,main_pressure,main_sea_level,main_grnd_level,main_humidity,main_temp_kf,main_dew_point,clouds_all,wind_speed,wind_deg,wind_gust,sys_pod,rain_3h,weather_id,weather_main,weather_description,weather_icon,datetime
0,1790326800,10000,0.0,2026-09-25 09:00:00,17.29,17.22,17.29,18.44,1020,1020,1018,82,-1.15,14.19,15,2.58,278,4.96,d,NaN,801,Clouds,few clouds,02d,2026-09-25 09:00:00
1,1790337600,10000,0.0,2026-09-25 12:00:00,18.14,18.12,18.14,19.84,1020,1020,1018,81,-1.70,14.83,23,5.05,306,8.68,d,NaN,801,Clouds,few clouds,02d,2026-09-25 12:00:00
2,1790348400,10000,0.0,2026-09-25 15:00:00,19.33,19.41,19.33,20.35,1019,1019,1018,80,-1.02,15.80,25,5.10,316,8.69,d,NaN,802,Clouds,scattered clouds,03d,2026-09-25 15:00:00
3,1790359200,10000,0.0,2026-09-25 18:00:00,16.61,16.55,16.61,16.61,1020,1020,1019,85,0.00,14.83,54,6.20,321,9.78,d,NaN,803,Clouds,broken clouds,04d,2026-09-25 18:00:00
4,1790370000,10000,0.0,2026-09-25 21:00:00,16.85,16.55,16.85,16.85,1021,1021,1020,75,0.00,13.82,98,5.86,325,8.87,n,NaN,804,Clouds,overcast clouds,04n,2026-09-25 21:00:00

In [15]:
# df_cities = pd.read_csv(os.path.join(DATA_DIR_CSV, "cities.csv"), encoding="utf-8")

# #weather_forecast = get_weather(lat, lon)

In [16]:
def summarize_weather(df: pd.DataFrame, hour_start: int = 8, hour_end: int = 20) -> pd.DataFrame:
    """ summarize weather on 5 days forecast
    compute daily rain and daily pop (probability of precipitation) between hour_start and hour_end
    """
    # define criteria 
    # compute summary on several criteria 
    # determine the top 7 cities with the best weather conditions for next 7 days
    #  daily.pop and daily.rain : expected volume of rain in next days 
    # temperature + humidity 
    
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"])
    df["date"] = df["datetime"].dt.date
    df["hour"] = df["datetime"].dt.hour

    mask = (df["hour"] >= hour_start) & (df["hour"] <= hour_end)
    day_df = df.loc[mask].copy()

    if "rain_3h" not in day_df.columns:
        day_df["rain_3h"] = 0
    if "pop" not in day_df.columns:
        day_df["pop"] = 0
        
    day_df['is_clear'] = day_df['weather_main'].isin(['Clear']) 
    day_df['is_rain'] = day_df['weather_main'].isin(['Rain', 'Drizzle', 'Thunderstorm'])
    day_df['main_temp'] = day_df['main_temp'].fillna(0)
    day_df['main_humidity'] = day_df['main_humidity'].fillna(0)
    day_df["rain_3h"] = day_df["rain_3h"].fillna(0)
    day_df["pop"] = day_df["pop"].fillna(0)
    day_df["wind_speed"] = day_df["wind_speed"].fillna(0)

    summary = day_df.groupby("date").agg(
        rain_sum=("rain_3h", "sum"),
        pop_max=("pop", "max"),
        temp_mean=("main_temp", "mean"),
        humidity_mean=("main_humidity", "mean"),
        clear_slots_count=("is_clear", "sum"),
        rain_slots_count=("is_rain", "sum"),
        wind_speed_max=("wind_speed", "max"),
        n_slots=("hour", "count"),
    ).reset_index()

    summary["clear_sky_ratio"] = summary["clear_slots_count"] / summary["n_slots"]
    summary["rain_ratio"] = summary["rain_slots_count"] / summary["n_slots"]


    # Critère booléen "jour agréable"
    summary["is_pleasant_day"] = (
        (summary["clear_sky_ratio"] >= 0.5)
        & summary["temp_mean"].between(15, 27)
        & (summary["humidity_mean"] < 70)
        & (summary["rain_sum"] < 0.5)
        & (summary["rain_slots_count"] == 0)
        & (summary["pop_max"] < 0.3)
        & (summary["wind_speed_max"] < 11)  # m/s ≈ 40 km/h
    )

    # Bonus : score continu (0 à 1) plutôt que binaire, plus nuancé
    summary["comfort_score"] = (
        0.30 * summary["clear_sky_ratio"]
        + 0.25 * (1 - (summary["humidity_mean"] / 100)).clip(0, 1)
        + 0.20 * (1 - summary["pop_max"]).clip(0, 1)
        + 0.15 * (1 - (summary["temp_mean"] - 21).abs() / 15).clip(0, 1)  # optimum ~21°C
        + 0.10 * (1 - (summary["wind_speed_max"] / 15)).clip(0, 1)
    ).clip(0, 1).round(2)

    return summary



    return summary


# daily_summary = summarize_weather(df_weather2)
# print(daily_summary)

In [17]:


def get_weather_data_for_cities(df_cities: pd.DataFrame) -> pd.DataFrame:
    results_weather = []
    for _, row in df_cities.iterrows():
        name = row['city_name']
        lat, lon = row['lat'], row['lon']
        
        # print(f"{name}\n")
        weather_forecast = get_weather(lat, lon)
        df_weather = compile_weather2(weather_forecast)
        
        sw = summarize_weather(df_weather)
        sw['city'] = name
        results_weather.append(sw)
        
        # display(sw)  # Optionally display the summary for each city
    
    return pd.concat(results_weather, ignore_index=True)

In [18]:
# select top 7 cities with best weather conditions for next 5 days : 
df_cities = results_df
result_weather = get_weather_data_for_cities(df_cities)
display(result_weather)

,date,rain_sum,pop_max,temp_mean,humidity_mean,clear_slots_count,rain_slots_count,wind_speed_max,n_slots,clear_sky_ratio,rain_ratio,is_pleasant_day,comfort_score,city
0,2026-09-25,0.00,0.00,19.2025,69.75,2,0,5.78,4,0.50,0.0,True,0.62,Mont Saint Michel
1,2026-09-26,0.00,0.00,18.8425,63.50,0,0,3.69,4,0.00,0.0,False,0.50,Mont Saint Michel
2,2026-09-27,4.48,1.00,20.5075,72.25,0,2,3.98,4,0.00,0.5,False,0.29,Mont Saint Michel
3,2026-09-28,4.50,1.00,18.3525,85.25,0,2,3.76,4,0.00,0.5,False,0.24,Mont Saint Michel
4,2026-09-29,0.00,0.19,23.5800,68.25,0,0,7.86,4,0.00,0.0,False,0.41,Mont Saint Michel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,2026-09-25,0.00,0.00,20.0850,57.50,0,0,2.13,4,0.00,0.0,False,0.53,Voiron
181,2026-09-26,0.00,0.00,25.2775,36.75,1,0,1.27,4,0.25,0.0,False,0.63,Voiron
182,2026-09-27,0.00,0.00,22.9475,51.50,4,0,3.65,4,1.00,0.0,True,0.83,Voiron
183,2026-09-28,0.00,0.00,21.2400,53.75,0,0,1.77,4,0.00,0.0,False,0.55,Voiron
184,2026-09-29,0.00,0.00,23.6650,42.75,0,0,3.00,4,0.00,0.0,False,0.55,Voiron

In [19]:

date_span = result_weather["date"].unique()
date_span

array([datetime.date(2026, 9, 25), datetime.date(2026, 9, 26),
       datetime.date(2026, 9, 27), datetime.date(2026, 9, 28),
       datetime.date(2026, 9, 29)], dtype=object)

In [20]:
print(len(date_span))
date_span[1]

5

datetime.date(2026, 9, 26)

In [21]:


def select_best_weather_cities(df_weather_summary: pd.DataFrame, top_n: int = 7, start_date: pd.Timestamp = None, end_date: pd.Timestamp = None) -> pd.DataFrame:
    """Select the top N cities with the best weather conditions based on comfort_score.
    between optional dates """
    # Group by city and calculate the average comfort score over the forecast period
    mask = df_weather_summary['date'].between(pd.Timestamp.now().date(), pd.Timestamp.now().date() + pd.Timedelta(days=5))
    df_weather_sub = df_weather_summary.loc[mask].copy()
    city_scores = df_weather_sub.groupby("city").agg(
        avg_comfort_score=("comfort_score", "mean")
    ).reset_index()

    # Sort by average comfort score in descending order and select top N cities
    top_cities = city_scores.sort_values("avg_comfort_score", ascending=False)
    top_cities['selected'] = 0
    top_cities.loc[top_cities.index[:top_n], 'selected'] = 1

    return top_cities


top_cities = select_best_weather_cities(result_weather, top_n=7)
# merge left with df_cities to get lat/lon for top cities
top_cities = top_cities.merge(df_cities[['city_name', 'lat', 'lon']], left_on='city', right_on='city_name', how='left')
top_cities = top_cities.drop(columns=['city_name'])  # Drop the duplicate city_name column after merge
display(top_cities[:7])

,city,avg_comfort_score,selected,lat,lon
0,Annecy,0.678,1,45.899235,6.128885
1,Colmar,0.674,1,48.077752,7.357964
2,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941
3,Besancon,0.660,1,47.238022,6.024362
4,Eguisheim,0.654,1,48.044797,7.307962
5,Strasbourg,0.652,1,48.584614,7.750713
6,Dijon,0.650,1,47.321581,5.041470

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like 😎 Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later 😉 You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

In [22]:
import plotly.express as px
# plot all cities wiith their average comfort score on a map of France
top_cities["marker_size"] = top_cities['selected'].map({1:15, 0:5})  # Example sizes for selected and non-selected cities
fig = px.scatter_mapbox(top_cities, 
                     lat="lat", 
                     lon="lon",
                     size="marker_size", 
                     size_max = 20,
                     hover_name="city", 
                     hover_data={"avg_comfort_score": ":.2f", "selected": True, "lat": False, "lon": False, "marker_size": False},
                     zoom=5,
                     center={"lat": 46.6, "lon": 2.5},
                     mapbox_style="open-street-map",
                     color="avg_comfort_score", 
                     color_continuous_scale=px.colors.sequential.Jet, 
                     #color_continuous_scale=px.colors.sequential.bluered, 
                     title="Top 7 Cities with Best Weather Conditions in France")
date_heure_today = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")
fig.update_layout(title=f"Indice de confort météo par ville; prévisions du {date_heure_today}", 
                  width = 900,
                  height=700,
                  margin=dict(l=0, r=0, t=40, b=0))
fig.show()

c:\work\Venv\venv_311_jedha\Lib\site-packages\kaleido\_sync_server.py:11: UserWarning:



Warning: You have Plotly version 5.24.1, which is not compatible with this version of Kaleido (1.2.0).

This means that static image generation (e.g. `fig.write_image()`) will not work.

Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.


### Scrape Booking.com 

Since BookingHoldings doesn't have aggregated databases, it will be much faster to scrape data directly from booking.com 

You can scrap as many information asyou want, but we suggest that you get at least:

*   hotel name,
*   Url to its booking.com page,
*   Its coordinates: latitude and longitude
*   Score given by the website users
*   Text description of the hotel

In [23]:
#https://www.booking.com/searchresults.fr.html?ss=Mont%2BSaint%2BMichel&ssne=Montauban&ssne_untouched=Montauban&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4ARfIAQ_YAQPoAQH4AQGIAgGoAgG4Arbzs9UGwAIB0gIkNzRkNzU5ZmUtZDM0MS00ZjIxLTlmZjctNjA1YjBiYjkzNWFi2AIB4AIB&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=900039327&dest_type=city&ac_meta=GhA2OGUxM2Q4YmYwMDcwYzY2IAAoATICZnI6EU1vbnQrU2FpbnQrTWljaGVs&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=68e13d8bf0070c66&checkin=2026-09-20&checkout=2026-09-21&group_adults=2&no_rooms=1&group_children=0

In [24]:
%load_ext autoreload
%autoreload 2  
# Recharge tous les modules avant chaque exécution de cellule

In [25]:
print(date_span[3])
print(date_span[4])

2026-09-28
2026-09-29

In [26]:
top_cities

,city,avg_comfort_score,selected,lat,lon,marker_size
0,Annecy,0.678,1,45.899235,6.128885,15
1,Colmar,0.674,1,48.077752,7.357964,15
2,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15
3,Besancon,0.660,1,47.238022,6.024362,15
4,Eguisheim,0.654,1,48.044797,7.307962,15
5,Strasbourg,0.652,1,48.584614,7.750713,15
6,Dijon,0.650,1,47.321581,5.041470,15
7,Lyon,0.628,0,45.757814,4.832011,5
8,Grenoble,0.628,0,45.187560,5.735782,5
9,Voiron,0.618,0,45.363139,5.591075,5
10,Gorges du Verdon,0.614,0,43.749656,6.328562,5
11,Aix en Provence,0.614,0,43.529842,5.447474,5
12,Montauban,0.600,0,44.017584,1.354999,5
13,Marseille,0.592,0,43.296399,5.377789,5
14,Bormes les Mimosas,0.588,0,43.150697,6.341928,5
15,Ariege,0.588,0,42.945537,1.406554,5
16,Issoudun,0.586,0,46.947766,1.988281,5
17,Toulouse,0.584,0,43.604464,1.444243,5
18,Paris,0.578,0,48.853495,2.348391,5
19,Avignon,0.570,0,43.949249,4.805901,5
20,Cassis,0.568,0,43.214036,5.539632,5
21,La Rochelle,0.544,0,46.159732,-1.151595,5
22,Lille,0.526,0,50.636565,3.063528,5
23,Uzes,0.524,0,44.012128,4.419672,5
24,Amiens,0.520,0,49.894171,2.295695,5
25,Carcassonne,0.510,0,43.213036,2.349107,5
26,Saintes Maries de la mer,0.498,0,43.451592,4.427720,5
27,Nimes,0.496,0,43.837425,4.360069,5
28,Rouen,0.468,0,49.440459,1.093966,5
29,Collioure,0.466,0,42.525050,3.083155,5
30,Bayeux,0.456,0,49.276462,-0.702474,5
31,Aigues Mortes,0.454,0,43.566152,4.191540,5
32,Le Havre,0.436,0,49.493898,0.107973,5
33,Bayonne,0.428,0,43.494514,-1.473666,5
34,Biarritz,0.422,0,43.483252,-1.559278,5
35,Mont Saint Michel,0.412,0,48.635954,-1.511460,5
36,St Malo,0.372,0,48.649518,-2.026041,5

In [29]:
import importlib
import booking_scraper_init
importlib.reload(booking_scraper_init)
from booking_scraper_init import get_hotel_availability, get_hotel_availability_sync

def save_city_hotel(city_name_: str, data):
    filename = f"{city_name_}_hotels.json"
    p = os.path.join(DATA_DIR_JSON_HOTELS, filename)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

In [32]:



from typing import Optional

import glob
import json
import os
from typing import Literal, Optional, Union
 



#clean data/json/hotels before new search

def collect_cities_hotels(top_cities,
                          checkin_date: str,
                         checkout_date: str,
                         n_adults: int = 2,
                         n_children: int = 0,
                         n_rooms: int = 1,
                         max_results: int = 20) -> pd.DataFrame:
    
    results_hotels = []

    for city in top_cities.loc[top_cities['selected'] == 1, 'city']:
        print(f"Searching hotels in {city}...")
        try:
            results = get_hotel_availability_sync(
                    city=city,
                    checkin_date=checkin_date,
                    checkout_date=checkout_date,
                    group_adults=n_adults,
                    group_children = n_children,
                    no_rooms=n_rooms,
                    max_results=max_results,
                )
        except Exception as e:
            print(f"Erreur pour {city} : {e}")
            continue # keep results already collected and go to next city
        city_name_ = clean_name(city) 
        # store all json results with {city}_hotels
        for h in results:
            h["city"] = city_name_
        
       
        save_city_hotel(city_name_, results)   # backup JSON individuel
        results_hotels.extend(results)         # <-- extend, pas append, et pas de réassignation

        print(json.dumps(results, ensure_ascii=False, indent=2))
        
    

    hotels_df = pd.DataFrame(results_hotels)
    hotels_df = hotels_df.drop_duplicates(subset="url", keep="first").reset_index(drop=True)
        
    return hotels_df

 
def select_top_hotels(
    df: pd.DataFrame,
    n: int = 20,
    criterion: Literal["score", "price", "combined"] = "combined",
    max_price: Optional[float] = None,
    out_all: Optional[bool] = False,
    ) -> pd.DataFrame:
    """
    Sélectionne les n meilleurs hôtels parmi toutes les villes, selon le
    critère choisi :
    - "score"    : meilleur score utilisateur d'abord (décroissant)
    - "price"    : prix le plus bas d'abord (croissant)
    - "combined" : parmi les hôtels avec price <= max_price, meilleur score
                   d'abord (décroissant)
 
    Les lignes sans 'score' ou 'price' (extraction ayant échoué) sont
    écartées avant classement.
 
    Lève ValueError si `criterion` est invalide, si 'combined' est demandé
    sans `max_price`, ou si les colonnes 'score'/'price' sont absentes.
    """
    # define penality : 
    p = (10-0)/1  # (score_max - score_min)/(min unity of price : 1 €)
    
    if criterion not in ("score", "price", "combined"):
        raise ValueError(f"criterion invalide : {criterion!r} (attendu 'score', 'price' ou 'combined')")
    if criterion == "combined" and max_price is None:
        raise ValueError("max_price est requis pour le critère 'combined'")
 
    missing = {"score", "price"} - set(df.columns)
    if missing:
        raise ValueError(f"Colonnes manquantes dans le DataFrame : {missing}")
 
    clean = df.dropna(subset=["score", "price"]).copy()
    if out_all:
        df['combined_score'] = df['score'] - p * (df['price'] - max_price).clip(lower=0)
        df = df.sort_values("combined_score", ascending=False)
        return df.reset_index(drop=True)
    
    else:  # default option : out_all=False
        if criterion == "score":
            ranked = clean.sort_values("score", ascending=False)
        elif criterion == "price":
            ranked = clean.sort_values("price", ascending=True)
        else:  # combined
            ranked = clean[clean["price"] <= max_price].sort_values("score", ascending=False)
    
        return ranked.head(n).reset_index(drop=True)

In [ ]:
# launch search hotels : 

checkin_date = "2026-09-25"
checkout_date = "2026-09-26"
# default journey dates : tomorrow - end of datespan :
checkin_date = date_span[1].isoformat()   # "2026-09-22"
checkout_date = date_span[-1].isoformat() # "2026-09-26"
n_adults = 2
n_children = 3
n_rooms = 2
max_results = 5

print('search hotels for top cities with best weather conditions')
print(top_cities.loc[top_cities['selected'] == 1, 'city'].tolist())
print(f"checkin_date: {checkin_date}, checkout_date: {checkout_date}, n_adults: {n_adults}, n_children: {n_children}, n_rooms: {n_rooms}, max_results: {max_results}")

#from aggregate_hotels import select_top_hotels
hotels_df = collect_cities_hotels(top_cities, checkin_date, checkout_date, n_adults, n_children, n_rooms, max_results)

search hotels for top cities with best weather conditions
['Annecy', 'Colmar', 'Chateau du Haut Koenigsbourg', 'Besancon', 'Eguisheim', 'Strasbourg', 'Dijon']
checkin_date: 2026-09-26, checkout_date: 2026-09-29, n_adults: 2, n_children: 3, n_rooms: 2, max_results: 5
Searching hotels in Annecy...
ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "B&B HOTEL Annecy Cran-Gevrier",
    "url": "https://www.booking.com/hotel/fr/b-amp-b-annecy-cran-gevrier.fr.html",
    "address": "16 Route de Nanfray, 74000 Annecy, France, 74000 16 Route de Nanfray, France",
    "hotel_description": "L’établissement B&B HOTEL Annecy Cran-Gevrier vous accueille à Annecy, à respectivement 4,7 km et 5 km de ces lieux d’intérêt : Château d'Annecy et Le...",
    "city": "Annecy",
    "latitude": 45.892319,
    "longitude": 6.0895437,
    "score": 7.8,
    "price": 580.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux\n2 lits simples\n1×\nChambre Triple\n2 lits (1 lit simple, 1 lit double)"
  },
  {
    "hotel_name": "Le Pélican",
    "url": "https://www.booking.com/hotel/fr/le-pelican-annecy1.fr.html",
    "address": "20 Rue des Marquisats, 74000 Annecy, France, 74000 20 Rue des Marquisats, France",
    "hotel_description": "L’établissement Le Pélican vous accueille à Annecy, à 400 mètres de ce lieu d’intérêt : Palais de l'Ile.",
    "city": "Annecy",
    "latitude": 45.897015,
    "longitude": 6.131543,
    "score": 8.8,
    "price": 3785.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Double ou Lits Jumeaux Classique avec Vue sur la Montagne\n1 grand lit double\nAucun prépaiement requis – Payez sur place\n1×\nMezzanine - Vue sur Lac\n2 grands lits doubles\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "Centre Jean XXIII",
    "url": "https://www.booking.com/hotel/fr/centre-jean-xxiii.fr.html",
    "address": "Annecy-le-Vieux 10 Chemin du Bray, 74940 Annecy, France, 74940 Annecy-le-Vieux 10 Chemin du Bray, France",
    "hotel_description": "Doté d’une terrasse bien exposée, le Centre Jean XXIII se trouve à Annecy, à 1,8 km du lac et à 3 km de la vieille ville.",
    "city": "Annecy",
    "latitude": 45.9183227,
    "longitude": 6.15250679999997,
    "score": 8.1,
    "price": 968.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Double Standard\n1 lit double • Lit bébé gratuit toujours disponible\nPetit-déjeuner compris\n1×\nAppartement avec Balcon\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n3 lits (2 lits simples, 1 lit double) • Lit bébé gratuit toujours disponible"
  },
  {
    "hotel_name": "Ibis Annecy - Cran-Gevrier",
    "url": "https://www.booking.com/hotel/fr/hotel-balladins-annecy-superior.fr.html",
    "address": "38, Avenue De La République, 74960 Annecy, France, 74960 38, Avenue De La République, France",
    "hotel_description": "L'Ibis Annecy - Cran-Gevrier se trouve à 5 minutes en voiture du centre d'Annecy et de son lac.",
    "city": "Annecy",
    "latitude": 45.907602953733,
    "longitude": 6.10762596130371,
    "score": 7.4,
    "price": 885.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n2 lits simples\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)"
  },
  {
    "hotel_name": "Impérial Palace",
    "url": "https://www.booking.com/hotel/fr/imperial-palace.fr.html",
    "address": "Allée de l'Impérial, 74000 Annecy, France, 74000 Allée de l'Impérial, France",
    "hotel_description": "Au cœur des Alpes françaises, l’Impérial Palace est un hôtel 4 étoiles qui se situe au bord du lac d’Annecy, à 1,6 km du centre d’Annecy.",
    "city": "Annecy",
    "latitude": 45.90374698623782,
    "longitude": 6.144694089889526,
    "score": 8.8,
    "price": 4416.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Lit Queen-Size Privilège avec Balcon - Accès au Spa Inclus - Réservation Nécessaire\n1 grand lit double\nAucun prépaiement requis – Payez sur place\n1×\nSuite Junior - Accès au Spa Inclus - Réservation Nécessaire\nPlusieurs types de lits\nAucun prépaiement requis – Payez sur place"
  }
]
Searching hotels in Colmar...
ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "ibis Budget Colmar Centre Gare",
    "url": "https://www.booking.com/hotel/fr/ibis-budget-colmar-centre-ville.fr.html",
    "address": "15 Rue Stanislas, 68000 Colmar, France, 68000 15 Rue Stanislas, France",
    "hotel_description": "L'ibis budget Colmar Centre Ville vous accueille à Colmar, dans le quartier du centre-ville, à 300 mètres de la Maison des Têtes et à 600 mètres de la...",
    "city": "Colmar",
    "latitude": 48.079697589205196,
    "longitude": 7.352361588954864,
    "score": 7.2,
    "price": 725.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n4 lits (2 lits simples, 2 lits doubles)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "ibis Colmar Est - Hotel Restaurant en Alsace",
    "url": "https://www.booking.com/hotel/fr/ibis-colmar-horbourg-wihr.fr.html",
    "address": "13, Route De Neuf-Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 13, Route De Neuf-Brisach - Horbourg Wihr, France",
    "hotel_description": "L'établissement ibis Colmar East - Hotel Brasserie en Alsace est situé à 5 km de la route des vins d'Alsace et à 10 km de Kaysersberg, Riquewihr et...",
    "city": "Colmar",
    "latitude": 48.07790332424113,
    "longitude": 7.402797639369965,
    "score": 7.4,
    "price": 611.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n1 lit simple\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "Hotel L'Europe Colmar, BW Signature Collection",
    "url": "https://www.booking.com/hotel/fr/l-europe.fr.html",
    "address": "15 route de Neuf Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 15 route de Neuf Brisach - Horbourg Wihr, France",
    "hotel_description": "Welcome to the Hotel & Restaurant l'Europe, located just 3 km from the pretty town of Colmar and its Petite Venise district, the Hotel Europe is your dream...",
    "city": "Colmar",
    "latitude": 48.0772062173984,
    "longitude": 7.403871864080429,
    "score": 8.6,
    "price": 971.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Confort sans Accès au Spa\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Familiale avec 1 Lit Queen-Size et 2 Lits Simples - Non-Fumeurs\n3 lits (2 lits simples, 1 grand lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "Unisotel Colmar Parc Des Exposition EX F1",
    "url": "https://www.booking.com/hotel/fr/f1-de-colmar.fr.html",
    "address": "36 Avenue de la Foire aux Vins, 68000 Colmar, France, 68000 36 Avenue de la Foire aux Vins, France",
    "hotel_description": "L’établissement Unisotel Colmar Parc Des Exposition EX F1 vous accueille à Colmar, à respectivement 800 mètres et 3,8 km de ces lieux d’intérêt : Parc des...",
    "city": "Colmar",
    "latitude": 48.10826,
    "longitude": 7.362704,
    "score": 4.3,
    "price": 270.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n2×\nChambre Triple avec Salle de Bains Commune\n4 lits (2 lits doubles, 2 lits superposés)"
  },
  {
    "hotel_name": "Duplex tout équipé, proche centre-ville COLMAR, parking",
    "url": "https://www.booking.com/hotel/fr/duplex-colore-et-bien-equipe-proche-centre-ville-colmar.fr.html",
    "address": "48 Rue du Ladhof, 68000 Colmar, France, 68000 48 Rue du Ladhof, France",
    "hotel_description": "L’hébergement Duplex tout équipé, proche centre-ville COLMAR, parking se situe à Colmar, à respectivement 1,4 km, 2,7 km et 3,2 km de ces lieux d’intérêt :...",
    "city": "Colmar",
    "latitude": 48.0860711,
    "longitude": 7.3678081,
    "score": 9.1,
    "price": 402.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 2 lits doubles)"
  }
]
Searching hotels in Chateau du Haut Koenigsbourg...
ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "Au pied du Château",
    "url": "https://www.booking.com/hotel/fr/au-pied-du-chateau-orschwiller.fr.html",
    "address": "Schaflager, 67600 Orschwiller, France, 67600 Schaflager, France",
    "hotel_description": "L’hébergement Au pied du Château se trouve à Orschwiller, à seulement 3,2 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",
    "city": "Chateau_du_Haut_Koenigsbourg",
    "latitude": 48.2484025,
    "longitude": 7.3548257,
    "score": 9.1,
    "price": 404.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement avec Vue sur la Montagne\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (2 lits doubles, 1 canapé-lit)"
  },
  {
    "hotel_name": "L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit",
    "url": "https://www.booking.com/hotel/fr/aubach-appartement-spacieux.fr.html",
    "address": "1 Rue de l'École, 67750 Scherwiller, France, 67750 1 Rue de l'École, France",
    "hotel_description": "L’hébergement L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit vous accueille à Scherwiller, à seulement 12 km de ce lieu d’intérêt...",
    "city": "Chateau_du_Haut_Koenigsbourg",
    "latitude": 48.2870641,
    "longitude": 7.4182105,
    "score": 7.9,
    "price": 332.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 119 m²\n3 lits (1 lit double, 1 très grand lit double, 1 grand lit double) • Lit bébé gratuit toujours disponible\nSéjour gratuit pour 2 de vos enfants"
  },
  {
    "hotel_name": "Gîte Le Faucon Pèlerin",
    "url": "https://www.booking.com/hotel/fr/gite-le-faucon-pelerin.fr.html",
    "address": "5 Rue du Taennelkreuz, 67750 Scherwiller, France, 67750 5 Rue du Taennelkreuz, France",
    "hotel_description": "L’hébergement Gîte Le Faucon Pèlerin se situe à Scherwiller, à respectivement 12 km et 24 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg et Parc...",
    "city": "Chateau_du_Haut_Koenigsbourg",
    "latitude": 48.288529886770505,
    "longitude": 7.416274561563467,
    "score": 9.3,
    "price": 322.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)"
  },
  {
    "hotel_name": "Gîtes Goettelmann Didier",
    "url": "https://www.booking.com/hotel/fr/gites-goettelmann-didier.fr.html",
    "address": "19 Rue de la Liberté, 67600 Kintzheim, France, 67600 19 Rue de la Liberté, France",
    "hotel_description": "L’établissement Gîtes Goettelmann Didier se trouve à Kintzheim (Alsace), à 7,5 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",
    "city": "Chateau_du_Haut_Koenigsbourg",
    "latitude": 48.2559074297705,
    "longitude": 7.39601948836059,
    "score": 9.2,
    "price": 299.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 1 Chambre\nMaison de vacances entière • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour vos enfants"
  },
  {
    "hotel_name": "Au petit randonneur",
    "url": "https://www.booking.com/hotel/fr/maison-au-petit-randonneur.fr.html",
    "address": "2 Rue église, 67220 Neubois, France, 67220 2 Rue église, France",
    "hotel_description": "L’hébergement Au petit randonneur vous accueille à Neubois, à respectivement 16 km, 10 km et 12 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg,...",
    "city": "Chateau_du_Haut_Koenigsbourg",
    "latitude": 48.306197995903,
    "longitude": 7.338326871689,
    "score": 9.5,
    "price": 360.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 80 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)"
  }
]
Searching hotels in Besancon...
ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "Premiere Classe Besancon Ecole Valentin",
    "url": "https://www.booking.com/hotel/fr/premiere-classe-besancon-ecole-valentin.fr.html",
    "address": "7 Route d'Epinal, 25480 Besançon, France, 25480 7 Route d'Epinal, France",
    "hotel_description": "Situé à proximité de l'Alsace et du Jura, cet hôtel est facilement accessible depuis l'autoroute A36.",
    "city": "Besancon",
    "latitude": 47.27044103591704,
    "longitude": 5.9982722997665405,
    "score": 6.9,
    "price": 272.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n2×\nChambre Triple (1 Lit Double et 1 Lit Simple)\n4 lits (2 lits doubles, 2 lits superposés)"
  },
  {
    "hotel_name": "Accueil Hotel Besançon",
    "url": "https://www.booking.com/hotel/fr/accueil-besancon.fr.html",
    "address": "6 Rue Louis Aragon, 25000 Besançon, France, 25000 6 Rue Louis Aragon, France",
    "hotel_description": "L’établissement Accueil Hotel Besançon se situe à Besançon, à respectivement 4,4 km et 7,9 km de ces lieux d’intérêt : Micropolis et Gare de...",
    "city": "Besancon",
    "latitude": 47.216012,
    "longitude": 5.9423711,
    "score": 5.5,
    "price": 216.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n2×\nChambre Double Standard\n4 lits (2 lits simples, 2 lits doubles)"
  },
  {
    "hotel_name": "ibis budget Besançon Centre Gare",
    "url": "https://www.booking.com/hotel/fr/ibis-budget-besanasson-centre-gare.fr.html",
    "address": "5, avenue Maréchal Foch, 25000 Besançon, France, 25000 5, avenue Maréchal Foch, France",
    "hotel_description": "Situé à Besançon, à seulement 100 mètres de la gare de la Viotte, l'ibis budget Besançon Centre Gare propose des chambres simples dotées d'une connexion...",
    "city": "Besancon",
    "latitude": 47.246846407466016,
    "longitude": 6.023120284080505,
    "score": 7.7,
    "price": 564.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nChambre Double\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Triple\n2 lits (1 lit double, 1 lit superposé)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "hotelF1 Besancon Ouest Micropolis",
    "url": "https://www.booking.com/hotel/fr/hotelf1-besancon-ouest-micropolis.fr.html",
    "address": "1 Rue Pierre Rubens, 25000 Besançon, France, 25000 1 Rue Pierre Rubens, France",
    "hotel_description": "L'hotelF1 Besancon Ouest Micropolis - vous accueille à Besançon, à 1 km du centre de conventions Micropolis.",
    "city": "Besancon",
    "latitude": 47.21853701449286,
    "longitude": 5.982121987766277,
    "score": 4.3,
    "price": 216.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n2×\nChambre Triple\n4 lits (2 lits doubles, 2 lits superposés)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
  },
  {
    "hotel_name": "Comfort Aparthotel Besancon Hauts du Chazal",
    "url": "https://www.booking.com/hotel/fr/residence-hauts-du-chazal.fr.html",
    "address": "26, rue Paul Milleret, 25000 Besançon, France, 25000 26, rue Paul Milleret, France",
    "hotel_description": "Installé à Besançon, à moins de 4,1 km du parc des expositions Micropolis, le Comfort Aparthotel Besancon Hauts du Chazal vous propose une terrasse, des...",
    "city": "Besancon",
    "latitude": 47.22448655881508,
    "longitude": 5.9561240673065186,
    "score": 7.9,
    "price": 630.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\n1×\nStudio Double\n1 lit double\n1×\nStudio Triple Standard\n2 lits (1 lit simple, 1 lit double)"
  }
]
Searching hotels in Eguisheim...
ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "Les Epicuriens du Rempart",
    "url": "https://www.booking.com/hotel/fr/maison-du-rempart-eguisheim.fr.html",
    "address": "14 Rue du Rempart Sud, 68420 Eguisheim, France, 68420 14 Rue du Rempart Sud, France",
    "hotel_description": "L’hébergement Les Epicuriens du Rempart vous accueille à Eguisheim, à respectivement 5,7 km, 6,5 km et 6,9 km de ces lieux d’intérêt : Gare de Colmar,...",
    "city": "Eguisheim",
    "latitude": 48.041846877148,
    "longitude": 7.305534992048,
    "score": 8.5,
    "price": 552.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 115 m²\n5 lits (4 lits simples, 1 lit double)"
  },
  {
    "hotel_name": "Le Zen",
    "url": "https://www.booking.com/hotel/fr/le-zen-eguisheim.fr.html",
    "address": "32 rue rempart sud, 68420 Eguisheim, France, 68420 32 rue rempart sud, France",
    "hotel_description": "L’hébergement Le Zen se trouve à Eguisheim, à respectivement 6,6 km et 7 km de ces lieux d’intérêt : Maison des Têtes et Collégiale Saint-Martin.",
    "city": "Eguisheim",
    "latitude": 48.04270935058594,
    "longitude": 7.304419994354248,
    "score": 7.5,
    "price": 443.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement Supérieur - Vue sur Ville\nAppartement entier • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit double, 2 canapés-lits)\nSéjour gratuit pour vos enfants"
  },
  {
    "hotel_name": "Les trois pierres",
    "url": "https://www.booking.com/hotel/fr/les-trois-pierres-eguisheim.fr.html",
    "address": "10 Rue des trois pierres, 68420 Eguisheim, France, 68420 10 Rue des trois pierres, France",
    "hotel_description": "L’hébergement Les trois pierres se situe à Eguisheim, à respectivement 6,1 km, 6,9 km et 7,4 km de ces lieux d’intérêt : Gare de Colmar, Maison des Têtes...",
    "city": "Eguisheim",
    "latitude": 48.045389099073,
    "longitude": 7.301809369312,
    "score": 8.8,
    "price": 862.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 2 salles de bains • 1 cuisine • 110 m²\n5 lits (2 lits simples, 1 canapé-lit, 2 grands lits doubles)"
  },
  {
    "hotel_name": "Charmante maison 3 chambres au cœur du vignoble avec terrasse",
    "url": "https://www.booking.com/hotel/fr/maison-voegtlinshoffen-5-pieces-6-personnes-fr-1-722-8.fr.html",
    "address": "4A rue du Schauenberg, 68420 Voegtlinshoffen, France, 68420 4A rue du Schauenberg, France",
    "hotel_description": "L’hébergement Charmante maison 3 chambres au cœur du vignoble avec terrasse vous accueille à respectivement 11 km et 12 km de ces lieux d’intérêt : Gare de...",
    "city": "Eguisheim",
    "latitude": 48.0198573,
    "longitude": 7.2809213,
    "score": 7.7,
    "price": 725.0,
    "currency": "EUR",

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [45]:

top20_hotels_combined = select_top_hotels(hotels_df, n=20, criterion="combined", max_price=500,out_all=True)

In [ ]:
top20_hotels_combined=top20_hotels_combined.rename(columns={'url':'url_hotel','address':'address_hotel','latitude':'lat_hotel','longitude':'lon_hotel','score':'score_hotel','price':'price_hotel','currency':'currency_hotel','combined_score':'combined_score_hotel'})

In [60]:
top20_hotels_combined = top20_hotels_combined.rename(columns={'city_hotel':'city'})

In [63]:
def extract_city(address: str) -> str | None:
    """Extrait la ville : entre ', CODE_POSTAL ' et la virgule suivante."""
    match = re.search(r",\s*\d{5}\s+([^,]+),", address)
    return match.group(1).strip() if match else None


top20_hotels_combined['hotel_city'] = top20_hotels_combined['address_hotel'].apply(extract_city)

In [64]:
display(top20_hotels_combined)

,hotel_name,url_hotel,address_hotel,hotel_description,city,lat_hotel,lon_hotel,score_hotel,price_hotel,currency_hotel,room_description,combined_score_hotel,hotel_city
0,Au petit randonneur,https://www.booking.com/hotel/fr/maison-au-petit-randonneur.fr.html,"2 Rue église, 67220 Neubois, France, 67220 2 Rue église, France","L’hébergement Au petit randonneur vous accueille à Neubois, à respectivement 16 km, 10 km et 12 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg,...",Chateau_du_Haut_Koenigsbourg,48.306198,7.338327,9.5,360.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 80 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)",9.5,Neubois
1,Gîtes intemporels d'Alsace,https://www.booking.com/hotel/fr/gites-intemporels-d-39-alsace.fr.html,"105 Route de Colmar, 68920 Wintzenheim, France, 68920 105 Route de Colmar, France","L’établissement Gîtes intemporels d'Alsace se trouve à Wintzenheim, à respectivement 2,7 km et 3,4 km de ces lieux d’intérêt : Gare de Colmar et Maison des...",Eguisheim,48.068011,7.317340,9.4,491.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 76 m²\n3 lits (1 canapé-lit, 2 grands lits doubles) • Lit bébé gratuit toujours disponible",9.4,Wintzenheim
2,Gîte Le Faucon Pèlerin,https://www.booking.com/hotel/fr/gite-le-faucon-pelerin.fr.html,"5 Rue du Taennelkreuz, 67750 Scherwiller, France, 67750 5 Rue du Taennelkreuz, France","L’hébergement Gîte Le Faucon Pèlerin se situe à Scherwiller, à respectivement 12 km et 24 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg et Parc...",Chateau_du_Haut_Koenigsbourg,48.288530,7.416275,9.3,322.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)",9.3,Scherwiller
3,Gîtes Goettelmann Didier,https://www.booking.com/hotel/fr/gites-goettelmann-didier.fr.html,"19 Rue de la Liberté, 67600 Kintzheim, France, 67600 19 Rue de la Liberté, France","L’établissement Gîtes Goettelmann Didier se trouve à Kintzheim (Alsace), à 7,5 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",Chateau_du_Haut_Koenigsbourg,48.255907,7.396019,9.2,299.0,EUR,"Recommandé pour votre groupe\nMaison 1 Chambre\nMaison de vacances entière • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour vos enfants",9.2,Kintzheim
4,Au pied du Château,https://www.booking.com/hotel/fr/au-pied-du-chateau-orschwiller.fr.html,"Schaflager, 67600 Orschwiller, France, 67600 Schaflager, France","L’hébergement Au pied du Château se trouve à Orschwiller, à seulement 3,2 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",Chateau_du_Haut_Koenigsbourg,48.248402,7.354826,9.1,404.0,EUR,"Recommandé pour votre groupe\nAppartement avec Vue sur la Montagne\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (2 lits doubles, 1 canapé-lit)",9.1,Orschwiller
5,"Duplex tout équipé, proche centre-ville COLMAR, parking",https://www.booking.com/hotel/fr/duplex-colore-et-bien-equipe-proche-centre-ville-colmar.fr.html,"48 Rue du Ladhof, 68000 Colmar, France, 68000 48 Rue du Ladhof, France","L’hébergement Duplex tout équipé, proche centre-ville COLMAR, parking se situe à Colmar, à respectivement 1,4 km, 2,7 km et 3,2 km de ces lieux d’intérêt :...",Colmar,48.086071,7.367808,9.1,402.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 2 lits doubles)",9.1,Colmar
6,L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit,https://www.booking.com/hotel/fr/aubach-appartement-spacieux.fr.html,"1 Rue de l'École, 67750 Scherwiller, France, 67750 1 Rue de l'École, France","L’hébergement L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit vous accueille à Scherwiller, à seulement 12 km de ce lieu d’intérêt...",Chateau_du_Haut_Koenigsbourg,48.287064,7.418210,7.9,332.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 119 m²\n3 lits (1 lit double, 1 très grand lit double, 1 grand lit double) • Lit bébé gratuit toujours disponible\nSéjour gratuit pour 2 de vos enfants",7.9,Scherwiller
7,ibis budget Dijon Saint Apollinaire,https://www.booking.com/hotel/fr/ibis-budget-dijon-saint-apollinaire.fr.html,"6 Rue Des Longenes (Saint-Apollinaire), 21850 Dijon, France, 21850 6 Rue Des Longenes (Saint-Apollinaire), France","L’établissement ibis budget Dijon Saint Apollinaire se trouve à Dijon, à 2 km de ce lieu d’intérêt : Parc des expositions et des congrès de Dijon.",Dijon,47.329601,5.077276,7.7,422.0,EUR,Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n2 lits doubles,7.7,Dijon
8,Le Zen,https://www.booking.com/hotel/fr/le-zen-eguisheim.fr.html,"32 rue rempart sud, 68420 Eguisheim, France, 68420 32 rue rempart sud, France","L’hébergement Le Zen se trouve à Eguisheim, à respectivement 6,6 km et 7 km de ces lieux d’intérêt : Maison des Têtes et Collégiale Saint-Martin.",Eguisheim,48.042709,7.304420,7.5,443.0,EUR,"Recommandé pour votre groupe\nAppartement Supérieur - Vue sur Ville\nAppartement entier • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit double, 2 canapés-lits)\nSéjour gratuit pour vos enfants",7.5,Eguisheim
9,Premiere Classe Besancon Ecole Valentin,https://www.booking.com/hotel/fr/premiere-classe-besancon-ecole-valentin.fr.html,"7 Route d'Epinal, 25480 Besançon, France, 25480 7 Route d'Epinal, France","Situé à proximité de l'Alsace et du Jura, cet hôtel est facilement accessible depuis l'autoroute A36.",Besancon,47.270441,5.998272,6.9,272.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple (1 Lit Double et 1 Lit Simple)\n4 lits (2 lits doubles, 2 lits superposés)",6.9,Besançon
10,Auberge de Jeunesse HI Strasbourg 2 Rives,https://www.booking.com/hotel/fr/auberge-de-jeunesse-hi-strasbourg.fr.html,"9 Rue des Cavaliers, 67000 Strasbourg, France, 67000 9 Rue des Cavaliers, France","L’établissement Auberge de Jeunesse HI Strasbourg 2 Rives se situe à Strasbourg, à 4,2 km de ce lieu d’intérêt : Jardin botanique de l'Université de...",Strasbourg,48.565861,7.800186,6.6,394.0,EUR,Recommandé pour votre groupe\n1×\nLit dans Dortoir pour Hommes de 3 Lits avec Salle de Bains Privative\nLit en dortoir • 16 m²\n1 lit simple\n1×\nChambre Quadruple avec Salle de Bains\n4 lits simples,6.6,Strasbourg
11,Premiere Classe Strasbourg Ouest,https://www.booking.com/hotel/fr/premiere-classe-strasbourg-ouest.fr.html,"6 Rue Cerf Berr, parc des poteries, 67200 Strasbourg, France, 67200 6 Rue Cerf Berr, parc des poteries, France",Le Premiere Classe Strasbourg Ouest est situé à 5 minutes en voiture du centre-ville et du Zénith de Strasbourg.,Strasbourg,48.587459,7.690129,6.3,431.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n6 lits (4 lits simples, 2 lits superposés)\nPetit-déjeuner compris\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",6.3,Strasbourg
12,Accueil Hotel Besançon,https://www.booking.com/hotel/fr/accueil-besancon.fr.html,"6 Rue Louis Aragon, 25000 Besançon, France, 25000 6 Rue Louis Aragon, France","L’établissement Accueil Hotel Besançon se situe à Besançon, à respectivement 4,4 km et 7,9 km de ces lieux d’intérêt : Micropolis et Gare de...",Besancon,47.216012,5.942371,5.5,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Standard\n4 lits (2 lits simples, 2 lits doubles)",5.5,Besançon
13,Unisotel Colmar Parc Des Exposition EX F1,https://www.booking.com/hotel/fr/f1-de-colmar.fr.html,"36 Avenue de la Foire aux Vins, 68000 Colmar, France, 68000 36 Avenue de la Foire aux Vins, France","L’établissement Unisotel Colmar Parc Des Exposition EX F1 vous accueille à Colmar, à respectivement 800 mètres et 3,8 km de ces lieux d’intérêt : Parc des...",Colmar,48.108260,7.362704,4.3,270.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec Salle de Bains Commune\n4 lits (2 lits doubles, 2 lits superposés)",4.3,Colmar
14,hotelF1 Besancon Ouest Micropolis,https://www.booking.com/hotel/fr/hotelf1-besancon-ouest-micropolis.fr.html,"1 Rue Pierre Rubens, 25000 Besançon, France, 25000 1 Rue Pierre Rubens, France","L'hotelF1 Besancon Ouest Micropolis - vous accueille à Besançon, à 1 km du centre de conventions Micropolis.",Besancon,47.218537,5.982122,4.3,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n4 lits (2 lits doubles, 2 lits superposés)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",4.3,Besançon
15,Les Epicuriens du Rempart,https://www.booking.com/hotel/fr/maison-du-rempart-eguisheim.fr.html,"14 Rue du Rempart Sud, 68420 Eguisheim, France, 68420 14 Rue du Rempart Sud, France","L’hébergement Les Epicuriens du Rempart vous accueille à Eguisheim, à respectivement 5,7 km, 6,5 km et 6,9 km de ces lieux d’intérêt : Gare de Colmar,...",Eguisheim,48.041847,7.305535,8.5,552.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 115 m²\n5 lits (4 lits simples, 1 lit double)",-511.5,Eguisheim
16,ibis budget Besançon Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-besanasson-centre-gare.fr.html,"5, avenue Maréchal Foch, 25000 Besançon, France, 25000 5, avenue Maréchal Foch, France","Situé à Besançon, à seulement 100 mètres de la gare de la Viotte, l'ibis budget Besançon Centre Gare propose des chambres simples dotées d'une connexion...",Besancon,47.246846,6.023120,7.7,564.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Triple\n2 lits (1 lit double, 1 lit superposé)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-632.3,Besançon
17,B&B HOTEL Annecy Cran-Gevrier,https://www.booking.com/hotel/fr/b-amp-b-annecy-cran-gevrier.fr.html,"16 Route de Nanfray, 74000 Annecy, France, 74000 16 Route de Nanfray, France","L’établissement B&B HOTEL Annecy Cran-Gevrier vous accueille à Annecy, à respectivement 4,7 km et 5 km de ces lieux d’intérêt : Château d'Annecy et Le...",Annecy,45.892319,6.089544,7.8,580.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux\n2 lits simples\n1×\nChambre Triple\n2 lits (1 lit simple, 1 lit double)",-792.2,Annecy
18,ibis Colmar Est - Hotel Restaurant en Alsace,https://www.booking.com/hotel/fr/ibis-colmar-horbourg-wihr.fr.html,"13, Route De Neuf-Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 13, Route De Neuf-Brisach - Horbourg Wihr, France","L'établissement ibis Colmar East - Hotel Brasserie en Alsace est situé à 5 km de la route des vins d'Alsace et à 10 km de Kaysersberg, Riquewihr et...",Colmar,48.077903,7.402798,7.4,611.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n1 lit simple\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1102.6,Colmar
19,Comfort Aparthotel Besancon Hauts du Chazal,https://www.booking.com/hotel/fr/residence-hauts-du-chazal.fr.html,"26, rue Paul Milleret, 25000 Besançon, France, 25000 26, rue Paul Milleret, France","Installé à Besançon, à moins de 4,1 km du parc des expositions Micropolis, le Comfort Aparthotel Besancon Hauts du Chazal vous propose une terrasse, des...",Besancon,47.224487,5.956124,7.9,630.0,EUR,"Recommandé pour votre groupe\n1×\nStudio Double\n1 lit double\n1×\nStudio Triple Standard\n2 lits (1 lit simple, 1 lit double)",-1292.1,Besançon
20,Appart'hôtel Odalys City - Dijon Centre Les Cordeliers,https://www.booking.com/hotel/fr/appart-39-odalys-les-cordeliers.fr.html,"3/5, rue Turgot, Centre-ville de Dijon, 21000 Dijon, France, 21000 3/5, rue Turgot, France",L’Appart'hôtel Odalys City - Dijon Centre Les Cordeliers vous accueille dans le centre historique de Dijon.,Dijon,47.318270,5.040115,8.1,645.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres (6 Adultes)\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)\nAnnulation gratuite étendue",-1441.9,Dijon
21,Novotel Dijon Sud,https://www.booking.com/hotel/fr/novotel-dijon-sud.fr.html,"11 Route De Beaune, 21160 Dijon, France, 21160 11 Route De Beaune, France","Situé sur la route des vins de Bourgogne, le Novotel Dijon Sud se trouve à 10 minutes de Dijon, dans la région des vignobles de Marsannay-la-Côte.",Dijon,47.279527,5.007706,7.1,673.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Classique avec Canapé-Lit\n4 lits (2 lits doubles, 2 canapés-lits)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1722.9,Dijon
22,Holiday Inn Dijon Toison D'or by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon.fr.html,"1 Place Marie de Bourgogne, 21000 Dijon, France, 21000 1 Place Marie de Bourgogne, France","Doté d'un spa avec un sauna, un hammam et une salle de sport, le Holiday Inn Dijon Toison D'or vous accueille en périphérie du centre-ville historique de...",Dijon,47.355700,5.052000,8.2,707.0,EUR,Recommandé pour votre groupe\n1×\nChambre 1 Lit Double Standard - Vue sur Ville\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Double Standard avec 2 Lits Doubles - Vue sur Ville\n2 lits doubles\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place,-2061.8,Dijon
23,Holiday Inn Dijon Sud - Longvic by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon-sud-longvic-an-ihg.fr.html,"3 RUE DE BEAUREGARD, 21600 Dijon, France, 21600 3 RUE DE BEAUREGARD, France","L’établissement Holiday Inn Dijon Sud - Longvic by IHG se trouve à Dijon, à 4,5 km de ce lieu d’intérêt : Arrêt de tramway Aéroport de Dijon-Bourgogne.",Dijon,47.272895,5.047662,8.8,712.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Standard Lit Queen-Size\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Lit Queen-Size Standard avec Canapé-Lit - Non-Fumeurs\n2 lits (1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2111.2,Dijon
24,Charmante maison 3 chambres au cœur du vignoble avec terrasse,https://www.booking.com/hotel/fr/maison-voegtlinshoffen-5-pieces-6-personnes-fr-1-722-8.fr.html,"4A rue du Schauenberg, 68420 Voegtlinshoffen, France, 68420 4A rue du Schauenberg, France",L’hébergement Charmante maison 3 chambres au cœur du vignoble avec terrasse vous accueille à respectivement 11 km et 12 km de ces lieux d’intérêt : Gare de...,Eguisheim,48.019857,7.280921,7.7,725.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salle de bains • 1 cuisine • 105 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)",-2242.3,Voegtlinshoffen
25,ibis Budget Colmar Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-colmar-centre-ville.fr.html,"15 Rue Stanislas, 68000 Colmar, France, 68000 15 Rue Stanislas, France","L'ibis budget Colmar Centre Ville vous accueille à Colmar, dans le quartier du centre-ville, à 300 mètres de la Maison des Têtes et à 600 mètres de la...",Colmar,48.079698,7.352362,7.2,725.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n4 lits (2 lits simples, 2 lits doubles)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2242.8,Colmar
26,Les trois pierres,https://www.booking.com/hotel/fr/les-trois-pierres-eguisheim.fr.html,"10 Rue des trois pierres, 68420 Eguisheim, France, 68420 10 Rue des trois pierres, France","L’hébergement Les trois pierres se situe à Eguisheim, à respectivement 6,1 km, 6,9 km et 7,4 km de ces lieux d’intérêt : Gare de Colmar, Maison des Têtes...",Eguisheim,48.045389,7.301809,8.8,862.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 2 salles de bains • 1 cuisine • 110 m²\n5 lits (2 lits simples, 1 canapé-lit, 2 grands lits doubles)",-3611.2,Eguisheim
27,Ibis Annecy - Cran-Gevrier,https://www.booking.com/hotel/fr/hotel-balladins-annecy-superior.fr.html,"38, Avenue De La République, 74960 Annecy, France, 74960 38, Avenue De La République, France",L'Ibis Annecy - Cran-Gevrier se trouve à 5 minutes en voiture du centre d'Annecy et de son lac.,Annecy,45.907603,6.107626,7.4,885.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n2 lits simples\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)",-3842.6,Annecy
28,Centre Jean XXIII,https://www.booking.com/hotel/fr/centre-jean-xxiii.fr.html,"Annecy-le-Vieux 10 Chemin du Bray, 74940 Annecy, France, 74940 Annecy-le-Vieux 10 Chemin du Bray, France","Doté d’une terrasse bien exposée, le Centre Jean XXIII se trouve à Annecy, à 1,8 km du lac et à 3 km de la vieille ville.",Annecy,45.918323,6.152507,8.1,968.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double Standard\n1 lit double • Lit bébé gratuit toujours disponible\nPetit-déjeuner compris\n1×\nAppartement avec Balcon\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n3 lits (2 lits simples, 1 lit double) • Lit bébé gratuit toujours disponible",-4671.9,Annecy
29,"Hotel L'Europe Colmar, BW Signature Collection",https://www.booking.com/hotel/fr/l-europe.fr.html,"15 route de Neuf Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 15 route de Neuf Brisach - Horbourg Wihr, France","Welcome to the Hotel & Restaurant l'Europe, located just 3 km from the pretty town of Colmar and its Petite Venise district, the Hotel Europe is your dream...",Colmar,48.077206,7.403872,8.6,971.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Confort sans Accès au Spa\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Familiale avec 1 Lit Queen-Size et 2 Lits Simples - Non-Fumeurs\n3 lits (2 lits simples, 1 grand lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-4701.4,Colmar
30,Les Appartements Rue des Veaux - Quartier Cathédrale,https://www.booking.com/hotel/fr/f2-quartier-cathedrale-2eme-etage.fr.html,"1 Rue des Veaux, 67000 Strasbourg, France, 67000 1 Rue des Veaux, France","L’établissement Les Appartements Rue des Veaux - Quartier Cathédrale se trouve à Strasbourg, à 400 mètres du centre et à 400 mètres de ce lieu d’intérêt :...",Strasbourg,48.581722,7.753513,8.5,980.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres - 2ème Étage\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 100 m²\n5 lits (2 canapés-lits, 3 grands lits doubles)",-4791.5,Strasbourg
31,Brit Hotel Strasbourg Le Lodge,https://www.booking.com/hotel/fr/brit-le-lodge.fr.html,"10 Rue Paul Eluard, 67200 Strasbourg, France, 67200 10 Rue Paul Eluard, France","Just 3 km from Strasbourg city centre, the Brit Hotel Le Lodge welcomes you to a modern, comfortable, and friendly setting.",Strasbourg,48.588294,7.697447,8.4,1215.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double Confort\n1 grand lit double\n1×\nChambre Familiale\n2 lits (1 canapé-lit, 1 grand lit double)",-7141.6,Strasbourg

In [ ]:
print("Top 20 hotels (combined score & price):")
display(top20_hotels_combined[["city", "hotel_name", "score", "price", "url","hotel_description","room_description"]])

Top 20 hotels (combined score & price):

,city,hotel_name,score,price,url,hotel_description,room_description
0,Chateau_du_Haut_Koenigsbourg,Chalet Les Prés,9.5,442.0,https://www.booking.com/hotel/fr/chalet-les-pres.fr.html,"L’hébergement Chalet Les Prés se situe à Neubois, à respectivement 16 km, 10 km et 12 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg, Cigoland et...","Recommandé pour votre groupe\nMaison de Vacances\nMaison de vacances entière • 3 chambres • 1 salle de bains • 1 cuisine • 90 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)"
1,Chateau_du_Haut_Koenigsbourg,Gîte Centre Alsace proche d’Europa Park,9.5,484.0,https://www.booking.com/hotel/fr/gite-centre-alsace-proche-d-europa-park.fr.html,"L’hébergement Gîte Centre Alsace proche d’Europa Park se trouve à Muttersholtz, à respectivement 25 km et 28 km de ces lieux d’intérêt : Musée Würth et...","Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 70 m²\n4 lits (2 lits simples, 1 canapé-lit, 1 grand lit double)"
2,Eguisheim,la petite maison,9.2,335.0,https://www.booking.com/hotel/fr/hdm-hebergement.fr.html,"Proposant un barbecue et offrant une vue sur la ville, l’hébergement la petite maison se trouve à Wintzenheim, à respectivement 5,6 km et 6,3 km de ces...","Recommandé pour votre groupe\nMaison de Vacances\nMaison de vacances entière • 3 chambres • 1 cuisine • 90 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)"
3,Colmar,Le Léon d'Or - Colmar - 4 ou 6 pers,9.1,389.0,https://www.booking.com/hotel/fr/le-leon-d-or-colmar-sleeps-6.fr.html,"L’hébergement Le Léon d'Or - Colmar - 4 ou 6 pers se trouve à Colmar, à respectivement 900 mètres, 1,2 km et 1,2 km de ces lieux d’intérêt : Maison des...","Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 76 m²\n3 lits (2 lits doubles, 1 canapé-lit)\nSéjour gratuit pour 1 de vos enfants"
4,Chateau_du_Haut_Koenigsbourg,Au pied du Château,9.1,404.0,https://www.booking.com/hotel/fr/au-pied-du-chateau-orschwiller.fr.html,"L’hébergement Au pied du Château se trouve à Orschwiller, à seulement 3,2 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.","Recommandé pour votre groupe\nAppartement avec Vue sur la Montagne\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (2 lits doubles, 1 canapé-lit)"
5,Chateau_du_Haut_Koenigsbourg,Gîte Jeanne familial - calme - parking,9.0,441.0,https://www.booking.com/hotel/fr/gite-chez-jeanne.fr.html,"L’hébergement Gîte Jeanne familial - calme - parking se situe à Ebersheim, à respectivement 19 km et 19 km de ces lieux d’intérêt : Château du...","Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 110 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)"
6,Dijon,Mustard Hostel,8.9,455.0,https://www.booking.com/hotel/fr/mustard-hostel.fr.html,"Proposant un jardin, un salon commun, un bar et une connexion Wi-Fi gratuite, l’établissement Mustard Hostel se situe à Dijon, à respectivement 400 mètres...","Recommandé pour votre groupe\n1×\nLit Simple dans Dortoir Mixte\nLit en dortoir • 18 m²\n1 lit superposé\n1×\nChambre Familiale avec Salle de Bains Commune\n3 lits (1 lit double, 2 lits superposés)"
7,Besancon,Hôtel AKENA Besançon,8.7,497.0,https://www.booking.com/hotel/fr/akena-besancon.fr.html,"L’établissement Hôtel AKENA Besançon vous accueille à Besançon, à 9 km de ce lieu d’intérêt : Micropolis.","Recommandé pour votre groupe\nChambre Familiale\n3 lits (2 canapés-lits, 1 grand lit double)"
8,Colmar,LE 16 - Très bel Appartement 3 chambres rénové pour 8 personnes,8.5,492.0,https://www.booking.com/hotel/fr/tres-bel-appartement-3-chambres-entierement-renove.fr.html,"L’hébergement LE 16 - Très bel Appartement 3 chambres rénové pour 8 personnes se trouve dans le centre de Colmar, à respectivement 500 mètres et 800 mètres...","Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 77 m²\n5 lits (2 lits simples, 1 lit double, 1 canapé-lit, 1 grand lit double)"
9,Chateau_du_Haut_Koenigsbourg,Gite Alize,8.5,337.0,https://www.booking.com/hotel/fr/gite-alize.fr.html,"L’hébergement Gite Alize se situe à Dambach-la-Ville, à respectivement 24 km, 11 km et 12 km de ces lieux d’intérêt : Musée Würth, Cigoland et Montagne des...","Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salle de bains • 1 cuisine • 95 m²\n6 lits (4 lits simples, 2 lits doubles)"
10,Chateau_du_Haut_Koenigsbourg,Gîte de charme au coeur du vignoble alsacien,8.2,186.0,https://www.booking.com/hotel/fr/gite-de-charme-au-coeur-du-vignoble-alsacien.fr.html,"Offrant une vue sur le jardin, l’hébergement Gîte de charme au coeur du vignoble alsacien se situe à Bernardvillé, à respectivement 24 km et 26 km de ces...","Recommandé pour votre groupe\nMaison 1 Chambre\nMaison de vacances entière • 1 chambre • 2 salons • 1 salle de bains • 1 cuisine • 80 m²\n4 lits (3 canapés-lits, 1 grand lit double)\nSéjour gratuit pour vos enfants"
11,Eguisheim,Résidence Pierre & Vacances Le Clos d'Eguisheim,8.1,430.0,https://www.booking.com/hotel/fr/residence-pierre-et-vacances-le-clos-d-eguisheim.fr.html,"Reception opening hours are Monday to Thursday from 08:30 to 12:00 and from 16:00 to 19:00, Friday from 08:30 to 12:00 and from 16:00 to 20:00, Saturday...","Recommandé pour votre groupe\nAppartement 1 Chambre avec Coin Nuit dans Alcôve - Vue sur Jardin (6 Personnes)\nAppartement entier • 1 chambre • 1 salon • 2 salles de bains • 46 m²\n2 lits (1 lit double, 1 canapé-lit)"
12,Colmar,Maisons neuves dans quartier calme,8.1,367.0,https://www.booking.com/hotel/fr/maisons-neuves-dans-quartier-calme.fr.html,"L’établissement Maisons neuves dans quartier calme se situe à Colmar, à respectivement 2,5 km et 2,9 km de ces lieux d’intérêt : Gare de Colmar et Maison...","Recommandé pour votre groupe\nMaison de Ville 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 100 m²\n5 lits (1 lit simple, 3 lits doubles, 1 canapé-lit)"
13,Strasbourg,Petit Manoir en Ville - Parking privé - 15 min Hyper-centre,8.1,489.0,https://www.booking.com/hotel/fr/petit-manoir-en-ville.fr.html,"L’hébergement Petit Manoir en Ville - Parking privé - 15 min Hyper-centre se situe à Strasbourg, à respectivement 2,9 km et 3,5 km de ces lieux d’intérêt :...","Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 2 salles de bains • 1 cuisine • 100 m²\n3 lits (2 lits doubles, 1 canapé-lit)"
14,Colmar,COLMAR - Appartements Deluxe - Lumineux - Stationnement Gratuit et Facile dans la rue,8.1,436.0,https://www.booking.com/hotel/fr/colmar-superbes-appartements-colmar.fr.html,"Proposant une connexion Wi-Fi gratuite et des hébergements avec vue sur la ville, l’établissement COLMAR - Appartements Deluxe - Lumineux - Stationnement...","Recommandé pour votre groupe\nAppartement avec Balcon\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n4 lits (2 lits simples, 1 canapé-lit, 1 grand lit double)"
15,Chateau_du_Haut_Koenigsbourg,Ibis Budget Sélestat,7.9,454.0,https://www.booking.com/hotel/fr/ibis-budget-selestat.fr.html,"Situé sur la route des vins d'Alsace, l'ibis Budget Sélestat se trouve à Sélestat. Une connexion Wi-Fi est disponible gratuitement.","Recommandé pour votre groupe\n2×\nChambre Double avec Lit Superposé\n4 lits (2 lits simples, 2 lits doubles)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
16,Besancon,B&B HOTEL Besançon Chateaufarine,7.8,483.0,https://www.booking.com/hotel/fr/b-amp-b-besancon.fr.html,"Doté d'une connexion Wi-Fi gratuite, le B&B HOTEL Besançon Chateaufarine propose des hébergements acceptant les animaux domestiques à 2 km du centre de...","Recommandé pour votre groupe\n1×\nChambre Double\n1 grand lit double\n1×\nChambre Triple\n2 lits (1 lit simple, 1 grand lit double)"
17,Grenoble,Adagio Grenoble Centre,7.8,326.0,https://www.booking.com/hotel/fr/hipark.fr.html,"L’Adagio Grenoble Centre est situé dans le quartier des affaires Europole, à 5 minutes à pied de la gare TGV de Grenoble et à 10 minutes de marche du...","Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 45 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"
18,Colmar,Gîtes La Petite Venise Colmar,7.7,373.0,https://www.booking.com/hotel/fr/15-rue-des-tisserands-colmar.fr.html,"L’établissement Gîtes La Petite Venise Colmar se trouve dans le centre de Colmar, à respectivement 1,2 km et 700 mètres de ces lieux d’intérêt : Gare de...","Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 45 m²\n3 lits (2 lits doubles, 1 canapé-lit)"
19,Besancon,ibis budget Besançon Centre Gare,7.7,456.0,https://www.booking.com/hotel/fr/ibis-budget-besanasson-centre-gare.fr.html,"Situé à Besançon, à seulement 100 mètres de la gare de la Viotte, l'ibis budget Besançon Centre Gare propose des chambres simples dotées d'une connexion...","Recommandé pour votre groupe\n1×\nChambre Double\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Triple\n2 lits (1 lit double, 1 lit superposé)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place"

In [38]:
top_cities.head()

,city,avg_comfort_score,selected,lat,lon,marker_size
0,Annecy,0.678,1,45.899235,6.128885,15
1,Colmar,0.674,1,48.077752,7.357964,15
2,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15
3,Besancon,0.660,1,47.238022,6.024362,15
4,Eguisheim,0.654,1,48.044797,7.307962,15

In [40]:
df_cities.head()

,city_name,city_name_,city_plus,lat,lon,city_id
0,Mont Saint Michel,Mont_Saint_Michel,Mont+Saint+Michel,48.635954,-1.511460,mont-saint-michel-4864-m151
1,St Malo,St_Malo,St+Malo,48.649518,-2.026041,st-malo-4865-m203
2,Bayeux,Bayeux,Bayeux,49.276462,-0.702474,bayeux-4928-m070
3,Le Havre,Le_Havre,Le+Havre,49.493898,0.107973,le-havre-4949-011
4,Rouen,Rouen,Rouen,49.440459,1.093966,rouen-4944-109

In [51]:
top_cities2 = top_cities.merge(df_cities.drop(columns=['lat','lon']),how='left',left_on='city',right_on='city_name')
top_cities2 = top_cities2.drop(columns=['city_name'])
top_cities2 = top_cities2.rename(columns={'lat':'lat_city','lon':'lon_city',})
top_cities2.head()

,city,avg_comfort_score,selected,lat_city,lon_city,marker_size,city_name_,city_plus,city_id
0,Annecy,0.678,1,45.899235,6.128885,15,Annecy,Annecy,annecy-4590-613
1,Colmar,0.674,1,48.077752,7.357964,15,Colmar,Colmar,colmar-4808-736
2,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734
3,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602
4,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731

In [39]:
result_weather.head()

,date,rain_sum,pop_max,temp_mean,humidity_mean,clear_slots_count,rain_slots_count,wind_speed_max,n_slots,clear_sky_ratio,rain_ratio,is_pleasant_day,comfort_score,city
0,2026-09-25,0.00,0.00,19.2025,69.75,2,0,5.78,4,0.5,0.0,True,0.62,Mont Saint Michel
1,2026-09-26,0.00,0.00,18.8425,63.50,0,0,3.69,4,0.0,0.0,False,0.50,Mont Saint Michel
2,2026-09-27,4.48,1.00,20.5075,72.25,0,2,3.98,4,0.0,0.5,False,0.29,Mont Saint Michel
3,2026-09-28,4.50,1.00,18.3525,85.25,0,2,3.76,4,0.0,0.5,False,0.24,Mont Saint Michel
4,2026-09-29,0.00,0.19,23.5800,68.25,0,0,7.86,4,0.0,0.0,False,0.41,Mont Saint Michel

In [72]:
cities_top20_hotels_2 = top_cities2.merge(top20_hotels_combined,how='outer',left_on='city_name_',right_on='city',suffixes=['_city','_hotel'])
cities_top20_hotels_2 = cities_top20_hotels_2.sort_values('combined_score_hotel',ascending=False)
cities_top20_hotels_2 = cities_top20_hotels_2.rename(
    columns = {'city_city':'city'}).drop(
        columns=['city_hotel'])
cities_top20_hotels_2

,city,avg_comfort_score,selected,lat_city,lon_city,marker_size,city_name_,city_plus,city_id,hotel_name,url_hotel,address_hotel,hotel_description,lat_hotel,lon_hotel,score_hotel,price_hotel,currency_hotel,room_description,combined_score_hotel,hotel_city
21,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734,Au petit randonneur,https://www.booking.com/hotel/fr/maison-au-petit-randonneur.fr.html,"2 Rue église, 67220 Neubois, France, 67220 2 Rue église, France","L’hébergement Au petit randonneur vous accueille à Neubois, à respectivement 16 km, 10 km et 12 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg,...",48.306198,7.338327,9.5,360.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 80 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)",9.5,Neubois
37,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731,Gîtes intemporels d'Alsace,https://www.booking.com/hotel/fr/gites-intemporels-d-39-alsace.fr.html,"105 Route de Colmar, 68920 Wintzenheim, France, 68920 105 Route de Colmar, France","L’établissement Gîtes intemporels d'Alsace se trouve à Wintzenheim, à respectivement 2,7 km et 3,4 km de ces lieux d’intérêt : Gare de Colmar et Maison des...",48.068011,7.317340,9.4,491.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 76 m²\n3 lits (1 canapé-lit, 2 grands lits doubles) • Lit bébé gratuit toujours disponible",9.4,Wintzenheim
22,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734,Gîte Le Faucon Pèlerin,https://www.booking.com/hotel/fr/gite-le-faucon-pelerin.fr.html,"5 Rue du Taennelkreuz, 67750 Scherwiller, France, 67750 5 Rue du Taennelkreuz, France","L’hébergement Gîte Le Faucon Pèlerin se situe à Scherwiller, à respectivement 12 km et 24 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg et Parc...",48.288530,7.416275,9.3,322.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)",9.3,Scherwiller
23,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734,Gîtes Goettelmann Didier,https://www.booking.com/hotel/fr/gites-goettelmann-didier.fr.html,"19 Rue de la Liberté, 67600 Kintzheim, France, 67600 19 Rue de la Liberté, France","L’établissement Gîtes Goettelmann Didier se trouve à Kintzheim (Alsace), à 7,5 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",48.255907,7.396019,9.2,299.0,EUR,"Recommandé pour votre groupe\nMaison 1 Chambre\nMaison de vacances entière • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour vos enfants",9.2,Kintzheim
27,Colmar,0.674,1,48.077752,7.357964,15,Colmar,Colmar,colmar-4808-736,"Duplex tout équipé, proche centre-ville COLMAR, parking",https://www.booking.com/hotel/fr/duplex-colore-et-bien-equipe-proche-centre-ville-colmar.fr.html,"48 Rue du Ladhof, 68000 Colmar, France, 68000 48 Rue du Ladhof, France","L’hébergement Duplex tout équipé, proche centre-ville COLMAR, parking se situe à Colmar, à respectivement 1,4 km, 2,7 km et 3,2 km de ces lieux d’intérêt :...",48.086071,7.367808,9.1,402.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 2 lits doubles)",9.1,Colmar
24,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734,Au pied du Château,https://www.booking.com/hotel/fr/au-pied-du-chateau-orschwiller.fr.html,"Schaflager, 67600 Orschwiller, France, 67600 Schaflager, France","L’hébergement Au pied du Château se trouve à Orschwiller, à seulement 3,2 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",48.248402,7.354826,9.1,404.0,EUR,"Recommandé pour votre groupe\nAppartement avec Vue sur la Montagne\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (2 lits doubles, 1 canapé-lit)",9.1,Orschwiller
25,Chateau du Haut Koenigsbourg,0.666,1,48.249382,7.343941,15,Chateau_du_Haut_Koenigsbourg,Chateau+du+Haut+Koenigsbourg,chateau-du-haut-koenigsbourg-4825-734,L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit,https://www.booking.com/hotel/fr/aubach-appartement-spacieux.fr.html,"1 Rue de l'École, 67750 Scherwiller, France, 67750 1 Rue de l'École, France","L’hébergement L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit vous accueille à Scherwiller, à seulement 12 km de ce lieu d’intérêt...",48.287064,7.418210,7.9,332.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 119 m²\n3 lits (1 lit double, 1 très grand lit double, 1 grand lit double) • Lit bébé gratuit toujours disponible\nSéjour gratuit pour 2 de vos enfants",7.9,Scherwiller
32,Dijon,0.650,1,47.321581,5.041470,15,Dijon,Dijon,dijon-4732-504,ibis budget Dijon Saint Apollinaire,https://www.booking.com/hotel/fr/ibis-budget-dijon-saint-apollinaire.fr.html,"6 Rue Des Longenes (Saint-Apollinaire), 21850 Dijon, France, 21850 6 Rue Des Longenes (Saint-Apollinaire), France","L’établissement ibis budget Dijon Saint Apollinaire se trouve à Dijon, à 2 km de ce lieu d’intérêt : Parc des expositions et des congrès de Dijon.",47.329601,5.077276,7.7,422.0,EUR,Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n2 lits doubles,7.7,Dijon
38,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731,Le Zen,https://www.booking.com/hotel/fr/le-zen-eguisheim.fr.html,"32 rue rempart sud, 68420 Eguisheim, France, 68420 32 rue rempart sud, France","L’hébergement Le Zen se trouve à Eguisheim, à respectivement 6,6 km et 7 km de ces lieux d’intérêt : Maison des Têtes et Collégiale Saint-Martin.",48.042709,7.304420,7.5,443.0,EUR,"Recommandé pour votre groupe\nAppartement Supérieur - Vue sur Ville\nAppartement entier • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit double, 2 canapés-lits)\nSéjour gratuit pour vos enfants",7.5,Eguisheim
12,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602,Premiere Classe Besancon Ecole Valentin,https://www.booking.com/hotel/fr/premiere-classe-besancon-ecole-valentin.fr.html,"7 Route d'Epinal, 25480 Besançon, France, 25480 7 Route d'Epinal, France","Situé à proximité de l'Alsace et du Jura, cet hôtel est facilement accessible depuis l'autoroute A36.",47.270441,5.998272,6.9,272.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple (1 Lit Double et 1 Lit Simple)\n4 lits (2 lits doubles, 2 lits superposés)",6.9,Besançon
57,Strasbourg,0.652,1,48.584614,7.750713,15,Strasbourg,Strasbourg,strasbourg-4858-775,Auberge de Jeunesse HI Strasbourg 2 Rives,https://www.booking.com/hotel/fr/auberge-de-jeunesse-hi-strasbourg.fr.html,"9 Rue des Cavaliers, 67000 Strasbourg, France, 67000 9 Rue des Cavaliers, France","L’établissement Auberge de Jeunesse HI Strasbourg 2 Rives se situe à Strasbourg, à 4,2 km de ce lieu d’intérêt : Jardin botanique de l'Université de...",48.565861,7.800186,6.6,394.0,EUR,Recommandé pour votre groupe\n1×\nLit dans Dortoir pour Hommes de 3 Lits avec Salle de Bains Privative\nLit en dortoir • 16 m²\n1 lit simple\n1×\nChambre Quadruple avec Salle de Bains\n4 lits simples,6.6,Strasbourg
58,Strasbourg,0.652,1,48.584614,7.750713,15,Strasbourg,Strasbourg,strasbourg-4858-775,Premiere Classe Strasbourg Ouest,https://www.booking.com/hotel/fr/premiere-classe-strasbourg-ouest.fr.html,"6 Rue Cerf Berr, parc des poteries, 67200 Strasbourg, France, 67200 6 Rue Cerf Berr, parc des poteries, France",Le Premiere Classe Strasbourg Ouest est situé à 5 minutes en voiture du centre-ville et du Zénith de Strasbourg.,48.587459,7.690129,6.3,431.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n6 lits (4 lits simples, 2 lits superposés)\nPetit-déjeuner compris\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",6.3,Strasbourg
13,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602,Accueil Hotel Besançon,https://www.booking.com/hotel/fr/accueil-besancon.fr.html,"6 Rue Louis Aragon, 25000 Besançon, France, 25000 6 Rue Louis Aragon, France","L’établissement Accueil Hotel Besançon se situe à Besançon, à respectivement 4,4 km et 7,9 km de ces lieux d’intérêt : Micropolis et Gare de...",47.216012,5.942371,5.5,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Standard\n4 lits (2 lits simples, 2 lits doubles)",5.5,Besançon
28,Colmar,0.674,1,48.077752,7.357964,15,Colmar,Colmar,colmar-4808-736,Unisotel Colmar Parc Des Exposition EX F1,https://www.booking.com/hotel/fr/f1-de-colmar.fr.html,"36 Avenue de la Foire aux Vins, 68000 Colmar, France, 68000 36 Avenue de la Foire aux Vins, France","L’établissement Unisotel Colmar Parc Des Exposition EX F1 vous accueille à Colmar, à respectivement 800 mètres et 3,8 km de ces lieux d’intérêt : Parc des...",48.108260,7.362704,4.3,270.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec Salle de Bains Commune\n4 lits (2 lits doubles, 2 lits superposés)",4.3,Colmar
14,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602,hotelF1 Besancon Ouest Micropolis,https://www.booking.com/hotel/fr/hotelf1-besancon-ouest-micropolis.fr.html,"1 Rue Pierre Rubens, 25000 Besançon, France, 25000 1 Rue Pierre Rubens, France","L'hotelF1 Besancon Ouest Micropolis - vous accueille à Besançon, à 1 km du centre de conventions Micropolis.",47.218537,5.982122,4.3,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n4 lits (2 lits doubles, 2 lits superposés)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",4.3,Besançon
39,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731,Les Epicuriens du Rempart,https://www.booking.com/hotel/fr/maison-du-rempart-eguisheim.fr.html,"14 Rue du Rempart Sud, 68420 Eguisheim, France, 68420 14 Rue du Rempart Sud, France","L’hébergement Les Epicuriens du Rempart vous accueille à Eguisheim, à respectivement 5,7 km, 6,5 km et 6,9 km de ces lieux d’intérêt : Gare de Colmar,...",48.041847,7.305535,8.5,552.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 115 m²\n5 lits (4 lits simples, 1 lit double)",-511.5,Eguisheim
15,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602,ibis budget Besançon Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-besanasson-centre-gare.fr.html,"5, avenue Maréchal Foch, 25000 Besançon, France, 25000 5, avenue Maréchal Foch, France","Situé à Besançon, à seulement 100 mètres de la gare de la Viotte, l'ibis budget Besançon Centre Gare propose des chambres simples dotées d'une connexion...",47.246846,6.023120,7.7,564.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Triple\n2 lits (1 lit double, 1 lit superposé)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-632.3,Besançon
3,Annecy,0.678,1,45.899235,6.128885,15,Annecy,Annecy,annecy-4590-613,B&B HOTEL Annecy Cran-Gevrier,https://www.booking.com/hotel/fr/b-amp-b-annecy-cran-gevrier.fr.html,"16 Route de Nanfray, 74000 Annecy, France, 74000 16 Route de Nanfray, France","L’établissement B&B HOTEL Annecy Cran-Gevrier vous accueille à Annecy, à respectivement 4,7 km et 5 km de ces lieux d’intérêt : Château d'Annecy et Le...",45.892319,6.089544,7.8,580.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux\n2 lits simples\n1×\nChambre Triple\n2 lits (1 lit simple, 1 lit double)",-792.2,Annecy
29,Colmar,0.674,1,48.077752,7.357964,15,Colmar,Colmar,colmar-4808-736,ibis Colmar Est - Hotel Restaurant en Alsace,https://www.booking.com/hotel/fr/ibis-colmar-horbourg-wihr.fr.html,"13, Route De Neuf-Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 13, Route De Neuf-Brisach - Horbourg Wihr, France","L'établissement ibis Colmar East - Hotel Brasserie en Alsace est situé à 5 km de la route des vins d'Alsace et à 10 km de Kaysersberg, Riquewihr et...",48.077903,7.402798,7.4,611.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n1 lit simple\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1102.6,Colmar
16,Besancon,0.660,1,47.238022,6.024362,15,Besancon,Besancon,besancon-4724-602,Comfort Aparthotel Besancon Hauts du Chazal,https://www.booking.com/hotel/fr/residence-hauts-du-chazal.fr.html,"26, rue Paul Milleret, 25000 Besançon, France, 25000 26, rue Paul Milleret, France","Installé à Besançon, à moins de 4,1 km du parc des expositions Micropolis, le Comfort Aparthotel Besancon Hauts du Chazal vous propose une terrasse, des...",47.224487,5.956124,7.9,630.0,EUR,"Recommandé pour votre groupe\n1×\nStudio Double\n1 lit double\n1×\nStudio Triple Standard\n2 lits (1 lit simple, 1 lit double)",-1292.1,Besançon
33,Dijon,0.650,1,47.321581,5.041470,15,Dijon,Dijon,dijon-4732-504,Appart'hôtel Odalys City - Dijon Centre Les Cordeliers,https://www.booking.com/hotel/fr/appart-39-odalys-les-cordeliers.fr.html,"3/5, rue Turgot, Centre-ville de Dijon, 21000 Dijon, France, 21000 3/5, rue Turgot, France",L’Appart'hôtel Odalys City - Dijon Centre Les Cordeliers vous accueille dans le centre historique de Dijon.,47.318270,5.040115,8.1,645.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres (6 Adultes)\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)\nAnnulation gratuite étendue",-1441.9,Dijon
34,Dijon,0.650,1,47.321581,5.041470,15,Dijon,Dijon,dijon-4732-504,Novotel Dijon Sud,https://www.booking.com/hotel/fr/novotel-dijon-sud.fr.html,"11 Route De Beaune, 21160 Dijon, France, 21160 11 Route De Beaune, France","Situé sur la route des vins de Bourgogne, le Novotel Dijon Sud se trouve à 10 minutes de Dijon, dans la région des vignobles de Marsannay-la-Côte.",47.279527,5.007706,7.1,673.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Classique avec Canapé-Lit\n4 lits (2 lits doubles, 2 canapés-lits)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1722.9,Dijon
35,Dijon,0.650,1,47.321581,5.041470,15,Dijon,Dijon,dijon-4732-504,Holiday Inn Dijon Toison D'or by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon.fr.html,"1 Place Marie de Bourgogne, 21000 Dijon, France, 21000 1 Place Marie de Bourgogne, France","Doté d'un spa avec un sauna, un hammam et une salle de sport, le Holiday Inn Dijon Toison D'or vous accueille en périphérie du centre-ville historique de...",47.355700,5.052000,8.2,707.0,EUR,Recommandé pour votre groupe\n1×\nChambre 1 Lit Double Standard - Vue sur Ville\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Double Standard avec 2 Lits Doubles - Vue sur Ville\n2 lits doubles\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place,-2061.8,Dijon
36,Dijon,0.650,1,47.321581,5.041470,15,Dijon,Dijon,dijon-4732-504,Holiday Inn Dijon Sud - Longvic by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon-sud-longvic-an-ihg.fr.html,"3 RUE DE BEAUREGARD, 21600 Dijon, France, 21600 3 RUE DE BEAUREGARD, France","L’établissement Holiday Inn Dijon Sud - Longvic by IHG se trouve à Dijon, à 4,5 km de ce lieu d’intérêt : Arrêt de tramway Aéroport de Dijon-Bourgogne.",47.272895,5.047662,8.8,712.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Standard Lit Queen-Size\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Lit Queen-Size Standard avec Canapé-Lit - Non-Fumeurs\n2 lits (1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2111.2,Dijon
40,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731,Charmante maison 3 chambres au cœur du vignoble avec terrasse,https://www.booking.com/hotel/fr/maison-voegtlinshoffen-5-pieces-6-personnes-fr-1-722-8.fr.html,"4A rue du Schauenberg, 68420 Voegtlinshoffen, France, 68420 4A rue du Schauenberg, France",L’hébergement Charmante maison 3 chambres au cœur du vignoble avec terrasse vous accueille à respectivement 11 km et 12 km de ces lieux d’intérêt : Gare de...,48.019857,7.280921,7.7,725.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salle de bains • 1 cuisine • 105 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)",-2242.3,Voegtlinshoffen
30,Colmar,0.674,1,48.077752,7.357964,15,Colmar,Colmar,colmar-4808-736,ibis Budget Colmar Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-colmar-centre-ville.fr.html,"15 Rue Stanislas, 68000 Colmar, France, 68000 15 Rue Stanislas, France","L'ibis budget Colmar Centre Ville vous accueille à Colmar, dans le quartier du centre-ville, à 300 mètres de la Maison des Têtes et à 600 mètres de la...",48.079698,7.352362,7.2,725.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n4 lits (2 lits simples, 2 lits doubles)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2242.8,Colmar
41,Eguisheim,0.654,1,48.044797,7.307962,15,Eguisheim,Eguisheim,eguisheim-4804-731,Les trois pierres,https://www.booking.com/hotel/fr/les-trois-pierres-eguisheim.fr.html,"10 Rue des trois pierres, 68420 Eguisheim, France, 68420 10 Rue des trois pierres, France","L’hébergement Les trois pierres se situe à Eguisheim, à respectivement 6,1 km, 6,9 km et 7,4 km de ces lieux d’intérêt : Gare de Colmar, Maison des Têtes...",48.045389,7.301809,8.8,862.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 2 salles de bains • 1 cuisine • 110 m²\n5 lits (2 lits simples, 1 canapé-lit, 2 grands lits doubles)",-3611.2,Eguisheim
4,Annecy,0.678,1,45.899235,6.128885,15,Annecy,Annecy,annecy-4590-613,Ibis Annecy - Cran-Gevrier,https://www.booking.com/hotel/fr/hotel-balladins-annecy-superior.fr.html,"38, Avenue De La République, 74960 Annecy, France, 74960 38, Avenue De La République, France",L'Ibis Annecy - Cran-Gevrier se trouve à 5 minutes en voiture du centre d'Annecy et de son lac.,45.907603,6.107626,7.4,885.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n2 lits simples\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)",-3842.6,Annecy
5,Annecy,0.678,1,45.899235,6.128885,15,Annecy,Annecy,annecy-4590-613,Centre Jean XXIII,https://www.booking.com/hotel/fr/centre-jean-xxiii.fr.html,"Annecy-le-Vieux 10 Chemin du Bray, 74940 Annecy, France, 74940 Annecy-le-Vieux 10 Chemin du Bray, France","Doté d’une terrasse bien exposée, le Centre Jean XXIII se trouve à Annecy, à 1,8 km du lac et à 3 km de la vieille ville.",45.918323,6.152507,8.1,968.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double Standard\n1 lit double • Lit bébé gratuit toujours disponible\nPetit-déjeuner compris\n1×\nAppartement avec Balcon\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n3 lits (2 lits simples, 1 lit double) • Lit bébé gratuit toujours disponible",-4671.9,Annecy

In [ ]:
city = "collioure"
results = get_hotel_availability_sync(
            city=city,
            checkin_date=checkin_date,
            checkout_date=checkout_date,
            group_adults=n_adults,
            no_rooms=n_rooms,
            max_results=max_results,
        )
print(json.dumps(results, ensure_ascii=False, indent=2))

ATTENTION : get_hotel_availability_sync() est un wrapper synchrone pour Jupyter/VSCode. Z
[
  {
    "hotel_name": "Ibanova Appartements",
    "url": "https://www.booking.com/hotel/fr/ibanova.fr.html",
    "address": "3 Rue du Soleil, 66190 Collioure, France, 66190 3 Rue du Soleil, France",
    "hotel_description": "L’établissement Ibanova Appartements se situe à Collioure (Languedoc-Roussillon), à proximité de ces lieux d’intérêt : Plage de Port d’Avall et Château...",
    "city": "3 Rue du Soleil",
    "latitude": 42.5231333,
    "longitude": 3.0855761,
    "score": 8.8,
    "price": 682.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement Supérieur avec Bain à Remous\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 95 m²\n2 lits doubles"
  },
  {
    "hotel_name": "APP' ART CENTRE PLAGE + PARKING GRATUIT",
    "url": "https://www.booking.com/hotel/fr/app-art-centre-plage-parking-gratuit.fr.html",
    "address": "13 Rue du Coma-Cheric, 66190 Collioure, France, 66190 13 Rue du Coma-Cheric, France",
    "hotel_description": "L’établissement APP' ART CENTRE PLAGE + PARKING GRATUIT se situe à Collioure (Languedoc-Roussillon), à proximité de ces lieux d’intérêt : Plage Boutigue et...",
    "city": "13 Rue du Coma-Cheric",
    "latitude": 42.5233452832972,
    "longitude": 3.08696843573436,
    "score": 8.5,
    "price": 513.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 50 m²\n3 lits (1 canapé-lit, 2 grands lits doubles)"
  },
  {
    "hotel_name": "T3 de CHARME a 20 m de la plage centre village",
    "url": "https://www.booking.com/hotel/fr/4-rue-nungesser-et-coli.fr.html",
    "address": "4 Rue Nungesser et Coli, 66190 Collioure, France, 66190 4 Rue Nungesser et Coli, France",
    "hotel_description": "Offrant une vue sur la ville, l’hébergement T3 de CHARME a 20 m de la plage centre village se trouve à Collioure, à respectivement quelques pas et 42 km de...",
    "city": "4 Rue Nungesser et Coli",
    "latitude": 42.5238821,
    "longitude": 3.0844023,
    "score": 8.2,
    "price": 365.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 45 m²\n3 lits (1 lit double, 2 canapés-lits)"
  },
  {
    "hotel_name": "Charmante Maison de Village à Collioure, Proche Plage - FR-1-309-464",
    "url": "https://www.booking.com/hotel/fr/maison-collioure-3-pieces-4-personnes-fr-1-309-464.fr.html",
    "address": "36 rue du soleil, 66190 Collioure, France, 66190 36 rue du soleil, France",
    "hotel_description": "L’hébergement 3 étoiles Charmante Maison de Village à Collioure, Proche Plage - FR-1-309-464 vous accueille à Collioure, dans la région...",
    "city": "36 rue du soleil",
    "latitude": 42.5232215,
    "longitude": 3.0844959,
    "score": 7.4,
    "price": 386.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salle de bains • 1 cuisine • 85 m²\n2 lits doubles"
  },
  {
    "hotel_name": "Superbe T3 vue sur mer parking privé classé 3 étoiles",
    "url": "https://www.booking.com/hotel/fr/appartement-spacieux-vue-sur-mer.fr.html",
    "address": "22 Route Impériale, 66190 Collioure, France, 66190 22 Route Impériale, France",
    "hotel_description": "Offrant une vue sur la mer, l’hébergement Superbe T3 vue sur mer parking privé classé 3 étoiles propose une piscine extérieure ouverte en saison, une...",
    "city": "22 Route Impériale",
    "latitude": 42.52269623927112,
    "longitude": 3.0924821386230583,
    "score": 9.0,
    "price": 620.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n4 lits (2 lits simples, 1 très grand lit double, 1 canapé-lit)"
  },
  {
    "hotel_name": "Maison de village au cœur de Collioure à 100m de la plage - FR-1-309-264",
    "url": "https://www.booking.com/hotel/fr/maison-collioure-3-pieces-5-personnes-fr-1-309-264.fr.html",
    "address": "7 Rue Arago, 66190 Collioure, France, 66190 7 Rue Arago, France",
    "hotel_description": "L’hébergement Maison de village au cœur de Collioure à 100m de la plage - FR-1-309-264 se situe à Collioure, à respectivement quelques pas, 42 km et 200...",
    "city": "7 Rue Arago",
    "latitude": 42.527572,
    "longitude": 3.0846323,
    "score": 8.0,
    "price": 415.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salle de bains • 1 cuisine • 82 m²\n4 lits (3 lits simples, 1 lit double)"
  },
  {
    "hotel_name": "Appartement T2 avec clim - 4 pers. à Collioure",
    "url": "https://www.booking.com/hotel/fr/appartement-t2-avec-clim-4-pers-a-collioure-fr-1-309-591.fr.html",
    "address": "Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2,, 66190 Collioure, France, 66190 Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2, France",
    "hotel_description": "Situé à Collioure, l’hébergement avec climatisation Appartement T2 avec clim - 4 pers. À Collioure comprend un balcon.",
    "city": "Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2",
    "latitude": 42.5208553,
    "longitude": 3.0872084,
    "score": 9.0,
    "price": 397.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 1 Chambre\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 40 m²\n2 lits (1 canapé-lit, 1 grand lit double)"
  },
  {
    "hotel_name": "T3 dans Résidence avec Parking et Piscine, situé au 3ème étage",
    "url": "https://www.booking.com/hotel/fr/t3-dans-residence-avec-parking-et-piscine.fr.html",
    "address": "Résidence du Port d'Avall, 66190 Collioure, France, 66190 Résidence du Port d'Avall, France",
    "hotel_description": "Offrant une vue sur la piscine, l’hébergement T3 dans Résidence avec Parking et Piscine, situé au 3ème étage possède une terrasse et un balcon, à environ...",
    "city": "Résidence du Port d'Avall",
    "latitude": 42.5221552,
    "longitude": 3.0885682,
    "score": 9.3,
    "price": 343.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres avec Balcon\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 60 m²\n2 lits (1 lit double, 1 grand lit double)"
  },
  {
    "hotel_name": "Appartement T3 calme avec terrasse et cuisine équipée, à 300m de la plage de Collioure - FR-1-309-246",
    "url": "https://www.booking.com/hotel/fr/appartement-collioure-3-pieces-4-personnes-fr-1-309-246.fr.html",
    "address": "9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche, 66190 Collioure, France, 66190 9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche, France",
    "hotel_description": "L’hébergement Appartement T3 calme avec terrasse et cuisine équipée, à 300m de la plage de Collioure - FR-1-309-246 vous accueille à respectivement 500...",
    "city": "9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche",
    "latitude": 42.5261183,
    "longitude": 3.0799531,
    "score": 7.1,
    "price": 387.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 66 m²\n2 lits (1 lit double, 1 canapé-lit)"
  },
  {
    "hotel_name": "Villa Solea Collioure",
    "url": "https://www.booking.com/hotel/fr/villa-solea-collioure.fr.html",
    "address": "VILLA SOLEA 3 La Creueta, 66190 Collioure, France, 66190 VILLA SOLEA 3 La Creueta, France",
    "hotel_description": "L’établissement Villa Solea Collioure vous accueille à Collioure, à respectivement 1,1 km et 43 km de ces lieux d’intérêt : Plage de Port d’Avall et Golf...",
    "city": "VILLA SOLEA 3 La Creueta",
    "latitude": 42.5222101,
    "longitude": 3.074082,
    "score": 6.8,
    "price": 850.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres avec Piscine Privée\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit superposé, 1 canapé-lit, 1 grand lit double)"
  }
]

In [ ]:
print(json.dumps(results, ensure_ascii=False, indent=2))

[
  {
    "hotel_name": "Ibanova Appartements",
    "url": "https://www.booking.com/hotel/fr/ibanova.fr.html",
    "address": "3 Rue du Soleil, 66190 Collioure, France, 66190 3 Rue du Soleil, France",
    "hotel_description": "L’établissement Ibanova Appartements se situe à Collioure (Languedoc-Roussillon), à proximité de ces lieux d’intérêt : Plage de Port d’Avall et Château...",
    "city": "3 Rue du Soleil",
    "latitude": 42.5231333,
    "longitude": 3.0855761,
    "score": 8.8,
    "price": 682.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement Supérieur avec Bain à Remous\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 95 m²\n2 lits doubles"
  },
  {
    "hotel_name": "APP' ART CENTRE PLAGE + PARKING GRATUIT",
    "url": "https://www.booking.com/hotel/fr/app-art-centre-plage-parking-gratuit.fr.html",
    "address": "13 Rue du Coma-Cheric, 66190 Collioure, France, 66190 13 Rue du Coma-Cheric, France",
    "hotel_description": "L’établissement APP' ART CENTRE PLAGE + PARKING GRATUIT se situe à Collioure (Languedoc-Roussillon), à proximité de ces lieux d’intérêt : Plage Boutigue et...",
    "city": "13 Rue du Coma-Cheric",
    "latitude": 42.5233452832972,
    "longitude": 3.08696843573436,
    "score": 8.5,
    "price": 513.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 50 m²\n3 lits (1 canapé-lit, 2 grands lits doubles)"
  },
  {
    "hotel_name": "T3 de CHARME a 20 m de la plage centre village",
    "url": "https://www.booking.com/hotel/fr/4-rue-nungesser-et-coli.fr.html",
    "address": "4 Rue Nungesser et Coli, 66190 Collioure, France, 66190 4 Rue Nungesser et Coli, France",
    "hotel_description": "Offrant une vue sur la ville, l’hébergement T3 de CHARME a 20 m de la plage centre village se trouve à Collioure, à respectivement quelques pas et 42 km de...",
    "city": "4 Rue Nungesser et Coli",
    "latitude": 42.5238821,
    "longitude": 3.0844023,
    "score": 8.2,
    "price": 365.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 45 m²\n3 lits (1 lit double, 2 canapés-lits)"
  },
  {
    "hotel_name": "Charmante Maison de Village à Collioure, Proche Plage - FR-1-309-464",
    "url": "https://www.booking.com/hotel/fr/maison-collioure-3-pieces-4-personnes-fr-1-309-464.fr.html",
    "address": "36 rue du soleil, 66190 Collioure, France, 66190 36 rue du soleil, France",
    "hotel_description": "L’hébergement 3 étoiles Charmante Maison de Village à Collioure, Proche Plage - FR-1-309-464 vous accueille à Collioure, dans la région...",
    "city": "36 rue du soleil",
    "latitude": 42.5232215,
    "longitude": 3.0844959,
    "score": 7.4,
    "price": 386.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salle de bains • 1 cuisine • 85 m²\n2 lits doubles"
  },
  {
    "hotel_name": "Superbe T3 vue sur mer parking privé classé 3 étoiles",
    "url": "https://www.booking.com/hotel/fr/appartement-spacieux-vue-sur-mer.fr.html",
    "address": "22 Route Impériale, 66190 Collioure, France, 66190 22 Route Impériale, France",
    "hotel_description": "Offrant une vue sur la mer, l’hébergement Superbe T3 vue sur mer parking privé classé 3 étoiles propose une piscine extérieure ouverte en saison, une...",
    "city": "22 Route Impériale",
    "latitude": 42.52269623927112,
    "longitude": 3.0924821386230583,
    "score": 9.0,
    "price": 620.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n4 lits (2 lits simples, 1 très grand lit double, 1 canapé-lit)"
  },
  {
    "hotel_name": "Maison de village au cœur de Collioure à 100m de la plage - FR-1-309-264",
    "url": "https://www.booking.com/hotel/fr/maison-collioure-3-pieces-5-personnes-fr-1-309-264.fr.html",
    "address": "7 Rue Arago, 66190 Collioure, France, 66190 7 Rue Arago, France",
    "hotel_description": "L’hébergement Maison de village au cœur de Collioure à 100m de la plage - FR-1-309-264 se situe à Collioure, à respectivement quelques pas, 42 km et 200...",
    "city": "7 Rue Arago",
    "latitude": 42.527572,
    "longitude": 3.0846323,
    "score": 8.0,
    "price": 415.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salle de bains • 1 cuisine • 82 m²\n4 lits (3 lits simples, 1 lit double)"
  },
  {
    "hotel_name": "Appartement T2 avec clim - 4 pers. à Collioure",
    "url": "https://www.booking.com/hotel/fr/appartement-t2-avec-clim-4-pers-a-collioure-fr-1-309-591.fr.html",
    "address": "Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2,, 66190 Collioure, France, 66190 Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2, France",
    "hotel_description": "Situé à Collioure, l’hébergement avec climatisation Appartement T2 avec clim - 4 pers. À Collioure comprend un balcon.",
    "city": "Rue Coma Cheric Rés. Val Saint - Elme, Bât. CARIOCA 2",
    "latitude": 42.5208553,
    "longitude": 3.0872084,
    "score": 9.0,
    "price": 397.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 1 Chambre\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 40 m²\n2 lits (1 canapé-lit, 1 grand lit double)"
  },
  {
    "hotel_name": "T3 dans Résidence avec Parking et Piscine, situé au 3ème étage",
    "url": "https://www.booking.com/hotel/fr/t3-dans-residence-avec-parking-et-piscine.fr.html",
    "address": "Résidence du Port d'Avall, 66190 Collioure, France, 66190 Résidence du Port d'Avall, France",
    "hotel_description": "Offrant une vue sur la piscine, l’hébergement T3 dans Résidence avec Parking et Piscine, situé au 3ème étage possède une terrasse et un balcon, à environ...",
    "city": "Résidence du Port d'Avall",
    "latitude": 42.5221552,
    "longitude": 3.0885682,
    "score": 9.3,
    "price": 343.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres avec Balcon\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 60 m²\n2 lits (1 lit double, 1 grand lit double)"
  },
  {
    "hotel_name": "Appartement T3 calme avec terrasse et cuisine équipée, à 300m de la plage de Collioure - FR-1-309-246",
    "url": "https://www.booking.com/hotel/fr/appartement-collioure-3-pieces-4-personnes-fr-1-309-246.fr.html",
    "address": "9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche, 66190 Collioure, France, 66190 9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche, France",
    "hotel_description": "L’hébergement Appartement T3 calme avec terrasse et cuisine équipée, à 300m de la plage de Collioure - FR-1-309-246 vous accueille à respectivement 500...",
    "city": "9 rue andré derain Résidence Michelet 1 er étage, appartement de gauche",
    "latitude": 42.5261183,
    "longitude": 3.0799531,
    "score": 7.1,
    "price": 387.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salle de bains • 1 cuisine • 66 m²\n2 lits (1 lit double, 1 canapé-lit)"
  },
  {
    "hotel_name": "Villa Solea Collioure",
    "url": "https://www.booking.com/hotel/fr/villa-solea-collioure.fr.html",
    "address": "VILLA SOLEA 3 La Creueta, 66190 Collioure, France, 66190 VILLA SOLEA 3 La Creueta, France",
    "hotel_description": "L’établissement Villa Solea Collioure vous accueille à Collioure, à respectivement 1,1 km et 43 km de ces lieux d’intérêt : Plage de Port d’Avall et Golf...",
    "city": "VILLA SOLEA 3 La Creueta",
    "latitude": 42.5222101,
    "longitude": 3.074082,
    "score": 6.8,
    "price": 850.0,
    "currency": "EUR",
    "room_description": "Recommandé pour votre groupe\nAppartement 2 Chambres avec Piscine Privée\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit superposé, 1 canapé-lit, 1 grand lit double)"
  }
]

In [ ]:
# function to aggregate hotels results : 

# function to select top 20 hotels in the cities selection :
# criteria 1 : top rated hotels 
# criteria2 :


### Create your data lake using S3 

Once you managed to build your dataset, you should store into S3 as a csv file.

In [ ]:
from jedha_Full_stack.Jedha_certif_CDSD.Block1.Kayak_weather_hotels.src.s3_utils import save_csv_to_s3, timestamped_filename

# Depuis un DataFrame (aucun fichier temporaire écrit sur disque)
uri = save_csv_to_s3(hotels_df, "hotels_top20.csv")
# -> s3://kayak-cyril/kayak/hotels_top20.csv

# Depuis un fichier .csv déjà sur disque
uri = save_csv_to_s3("hotels_lyon.csv", "hotels_lyon.csv")

# Nom de fichier horodaté (évite d'écraser un upload précédent)
uri = save_csv_to_s3(hotels_df, timestamped_filename("hotels"))


### ETL 

Once you uploaded your data onto S3, it will be better for the next data analysis team to extract clean data directly from a Data Warehouse. Therefore, create a SQL Database using AWS RDS, extract your data from S3 and store it in your newly created DB.

In [76]:
# read .csv file with cities, weather, hotels 
# and select top 20 hotels with best score and price
cities_cols = ['city_id','city','lat_city','lon_city','city_name_','city_plus']
hotels_cols = ['city','hotel_name','url_hotel','address_hotel','hotel_description',
                   'lat_hotel',	'lon_hotel','score_hotel','price_hotel','currency_hotel',
                   'room_description','combined_score_hotel','hotel_city']
# transform cities_df to have one row per city with all information about the city, weather, etc.
cities_bis = cities_top20_hotels_2[cities_cols].dropna().drop_duplicates()
cities_bis
# transform hotels_df to have one row per hotel with all information about the hotel and the city, weather, etc.
hotels_bis = cities_top20_hotels_2[hotels_cols].dropna().drop_duplicates()
hotels_bis

# transform weather_df to have one row per time slot per city with all information about the weather and the city, hotels, etc.

# load cities into AWS RDS database 

# load hotels in RDS database 

# load

,city,hotel_name,url_hotel,address_hotel,hotel_description,lat_hotel,lon_hotel,score_hotel,price_hotel,currency_hotel,room_description,combined_score_hotel,hotel_city
21,Chateau du Haut Koenigsbourg,Au petit randonneur,https://www.booking.com/hotel/fr/maison-au-petit-randonneur.fr.html,"2 Rue église, 67220 Neubois, France, 67220 2 Rue église, France","L’hébergement Au petit randonneur vous accueille à Neubois, à respectivement 16 km, 10 km et 12 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg,...",48.306198,7.338327,9.5,360.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 80 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)",9.5,Neubois
37,Eguisheim,Gîtes intemporels d'Alsace,https://www.booking.com/hotel/fr/gites-intemporels-d-39-alsace.fr.html,"105 Route de Colmar, 68920 Wintzenheim, France, 68920 105 Route de Colmar, France","L’établissement Gîtes intemporels d'Alsace se trouve à Wintzenheim, à respectivement 2,7 km et 3,4 km de ces lieux d’intérêt : Gare de Colmar et Maison des...",48.068011,7.317340,9.4,491.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 76 m²\n3 lits (1 canapé-lit, 2 grands lits doubles) • Lit bébé gratuit toujours disponible",9.4,Wintzenheim
22,Chateau du Haut Koenigsbourg,Gîte Le Faucon Pèlerin,https://www.booking.com/hotel/fr/gite-le-faucon-pelerin.fr.html,"5 Rue du Taennelkreuz, 67750 Scherwiller, France, 67750 5 Rue du Taennelkreuz, France","L’hébergement Gîte Le Faucon Pèlerin se situe à Scherwiller, à respectivement 12 km et 24 km de ces lieux d’intérêt : Château du Haut-Kœnigsbourg et Parc...",48.288530,7.416275,9.3,322.0,EUR,"Recommandé pour votre groupe\nMaison 2 Chambres\nMaison de vacances entière • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)",9.3,Scherwiller
23,Chateau du Haut Koenigsbourg,Gîtes Goettelmann Didier,https://www.booking.com/hotel/fr/gites-goettelmann-didier.fr.html,"19 Rue de la Liberté, 67600 Kintzheim, France, 67600 19 Rue de la Liberté, France","L’établissement Gîtes Goettelmann Didier se trouve à Kintzheim (Alsace), à 7,5 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",48.255907,7.396019,9.2,299.0,EUR,"Recommandé pour votre groupe\nMaison 1 Chambre\nMaison de vacances entière • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit simple, 1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour vos enfants",9.2,Kintzheim
27,Colmar,"Duplex tout équipé, proche centre-ville COLMAR, parking",https://www.booking.com/hotel/fr/duplex-colore-et-bien-equipe-proche-centre-ville-colmar.fr.html,"48 Rue du Ladhof, 68000 Colmar, France, 68000 48 Rue du Ladhof, France","L’hébergement Duplex tout équipé, proche centre-ville COLMAR, parking se situe à Colmar, à respectivement 1,4 km, 2,7 km et 3,2 km de ces lieux d’intérêt :...",48.086071,7.367808,9.1,402.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salle de bains • 1 cuisine • 70 m²\n3 lits (1 lit simple, 2 lits doubles)",9.1,Colmar
24,Chateau du Haut Koenigsbourg,Au pied du Château,https://www.booking.com/hotel/fr/au-pied-du-chateau-orschwiller.fr.html,"Schaflager, 67600 Orschwiller, France, 67600 Schaflager, France","L’hébergement Au pied du Château se trouve à Orschwiller, à seulement 3,2 km de ce lieu d’intérêt : Château du Haut-Kœnigsbourg.",48.248402,7.354826,9.1,404.0,EUR,"Recommandé pour votre groupe\nAppartement avec Vue sur la Montagne\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (2 lits doubles, 1 canapé-lit)",9.1,Orschwiller
25,Chateau du Haut Koenigsbourg,L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit,https://www.booking.com/hotel/fr/aubach-appartement-spacieux.fr.html,"1 Rue de l'École, 67750 Scherwiller, France, 67750 1 Rue de l'École, France","L’hébergement L'Aubach - appartement spacieux - au pied du vignoble - parking gratuit vous accueille à Scherwiller, à seulement 12 km de ce lieu d’intérêt...",48.287064,7.418210,7.9,332.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 119 m²\n3 lits (1 lit double, 1 très grand lit double, 1 grand lit double) • Lit bébé gratuit toujours disponible\nSéjour gratuit pour 2 de vos enfants",7.9,Scherwiller
32,Dijon,ibis budget Dijon Saint Apollinaire,https://www.booking.com/hotel/fr/ibis-budget-dijon-saint-apollinaire.fr.html,"6 Rue Des Longenes (Saint-Apollinaire), 21850 Dijon, France, 21850 6 Rue Des Longenes (Saint-Apollinaire), France","L’établissement ibis budget Dijon Saint Apollinaire se trouve à Dijon, à 2 km de ce lieu d’intérêt : Parc des expositions et des congrès de Dijon.",47.329601,5.077276,7.7,422.0,EUR,Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n2 lits doubles,7.7,Dijon
38,Eguisheim,Le Zen,https://www.booking.com/hotel/fr/le-zen-eguisheim.fr.html,"32 rue rempart sud, 68420 Eguisheim, France, 68420 32 rue rempart sud, France","L’hébergement Le Zen se trouve à Eguisheim, à respectivement 6,6 km et 7 km de ces lieux d’intérêt : Maison des Têtes et Collégiale Saint-Martin.",48.042709,7.304420,7.5,443.0,EUR,"Recommandé pour votre groupe\nAppartement Supérieur - Vue sur Ville\nAppartement entier • 1 chambre • 1 salon • 1 salle de bains • 1 cuisine • 60 m²\n3 lits (1 lit double, 2 canapés-lits)\nSéjour gratuit pour vos enfants",7.5,Eguisheim
12,Besancon,Premiere Classe Besancon Ecole Valentin,https://www.booking.com/hotel/fr/premiere-classe-besancon-ecole-valentin.fr.html,"7 Route d'Epinal, 25480 Besançon, France, 25480 7 Route d'Epinal, France","Situé à proximité de l'Alsace et du Jura, cet hôtel est facilement accessible depuis l'autoroute A36.",47.270441,5.998272,6.9,272.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple (1 Lit Double et 1 Lit Simple)\n4 lits (2 lits doubles, 2 lits superposés)",6.9,Besançon
57,Strasbourg,Auberge de Jeunesse HI Strasbourg 2 Rives,https://www.booking.com/hotel/fr/auberge-de-jeunesse-hi-strasbourg.fr.html,"9 Rue des Cavaliers, 67000 Strasbourg, France, 67000 9 Rue des Cavaliers, France","L’établissement Auberge de Jeunesse HI Strasbourg 2 Rives se situe à Strasbourg, à 4,2 km de ce lieu d’intérêt : Jardin botanique de l'Université de...",48.565861,7.800186,6.6,394.0,EUR,Recommandé pour votre groupe\n1×\nLit dans Dortoir pour Hommes de 3 Lits avec Salle de Bains Privative\nLit en dortoir • 16 m²\n1 lit simple\n1×\nChambre Quadruple avec Salle de Bains\n4 lits simples,6.6,Strasbourg
58,Strasbourg,Premiere Classe Strasbourg Ouest,https://www.booking.com/hotel/fr/premiere-classe-strasbourg-ouest.fr.html,"6 Rue Cerf Berr, parc des poteries, 67200 Strasbourg, France, 67200 6 Rue Cerf Berr, parc des poteries, France",Le Premiere Classe Strasbourg Ouest est situé à 5 minutes en voiture du centre-ville et du Zénith de Strasbourg.,48.587459,7.690129,6.3,431.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n6 lits (4 lits simples, 2 lits superposés)\nPetit-déjeuner compris\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",6.3,Strasbourg
13,Besancon,Accueil Hotel Besançon,https://www.booking.com/hotel/fr/accueil-besancon.fr.html,"6 Rue Louis Aragon, 25000 Besançon, France, 25000 6 Rue Louis Aragon, France","L’établissement Accueil Hotel Besançon se situe à Besançon, à respectivement 4,4 km et 7,9 km de ces lieux d’intérêt : Micropolis et Gare de...",47.216012,5.942371,5.5,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Standard\n4 lits (2 lits simples, 2 lits doubles)",5.5,Besançon
28,Colmar,Unisotel Colmar Parc Des Exposition EX F1,https://www.booking.com/hotel/fr/f1-de-colmar.fr.html,"36 Avenue de la Foire aux Vins, 68000 Colmar, France, 68000 36 Avenue de la Foire aux Vins, France","L’établissement Unisotel Colmar Parc Des Exposition EX F1 vous accueille à Colmar, à respectivement 800 mètres et 3,8 km de ces lieux d’intérêt : Parc des...",48.108260,7.362704,4.3,270.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec Salle de Bains Commune\n4 lits (2 lits doubles, 2 lits superposés)",4.3,Colmar
14,Besancon,hotelF1 Besancon Ouest Micropolis,https://www.booking.com/hotel/fr/hotelf1-besancon-ouest-micropolis.fr.html,"1 Rue Pierre Rubens, 25000 Besançon, France, 25000 1 Rue Pierre Rubens, France","L'hotelF1 Besancon Ouest Micropolis - vous accueille à Besançon, à 1 km du centre de conventions Micropolis.",47.218537,5.982122,4.3,216.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple\n4 lits (2 lits doubles, 2 lits superposés)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",4.3,Besançon
39,Eguisheim,Les Epicuriens du Rempart,https://www.booking.com/hotel/fr/maison-du-rempart-eguisheim.fr.html,"14 Rue du Rempart Sud, 68420 Eguisheim, France, 68420 14 Rue du Rempart Sud, France","L’hébergement Les Epicuriens du Rempart vous accueille à Eguisheim, à respectivement 5,7 km, 6,5 km et 6,9 km de ces lieux d’intérêt : Gare de Colmar,...",48.041847,7.305535,8.5,552.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 115 m²\n5 lits (4 lits simples, 1 lit double)",-511.5,Eguisheim
15,Besancon,ibis budget Besançon Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-besanasson-centre-gare.fr.html,"5, avenue Maréchal Foch, 25000 Besançon, France, 25000 5, avenue Maréchal Foch, France","Situé à Besançon, à seulement 100 mètres de la gare de la Viotte, l'ibis budget Besançon Centre Gare propose des chambres simples dotées d'une connexion...",47.246846,6.023120,7.7,564.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Triple\n2 lits (1 lit double, 1 lit superposé)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-632.3,Besançon
3,Annecy,B&B HOTEL Annecy Cran-Gevrier,https://www.booking.com/hotel/fr/b-amp-b-annecy-cran-gevrier.fr.html,"16 Route de Nanfray, 74000 Annecy, France, 74000 16 Route de Nanfray, France","L’établissement B&B HOTEL Annecy Cran-Gevrier vous accueille à Annecy, à respectivement 4,7 km et 5 km de ces lieux d’intérêt : Château d'Annecy et Le...",45.892319,6.089544,7.8,580.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux\n2 lits simples\n1×\nChambre Triple\n2 lits (1 lit simple, 1 lit double)",-792.2,Annecy
29,Colmar,ibis Colmar Est - Hotel Restaurant en Alsace,https://www.booking.com/hotel/fr/ibis-colmar-horbourg-wihr.fr.html,"13, Route De Neuf-Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 13, Route De Neuf-Brisach - Horbourg Wihr, France","L'établissement ibis Colmar East - Hotel Brasserie en Alsace est situé à 5 km de la route des vins d'Alsace et à 10 km de Kaysersberg, Riquewihr et...",48.077903,7.402798,7.4,611.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n1 lit simple\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1102.6,Colmar
16,Besancon,Comfort Aparthotel Besancon Hauts du Chazal,https://www.booking.com/hotel/fr/residence-hauts-du-chazal.fr.html,"26, rue Paul Milleret, 25000 Besançon, France, 25000 26, rue Paul Milleret, France","Installé à Besançon, à moins de 4,1 km du parc des expositions Micropolis, le Comfort Aparthotel Besancon Hauts du Chazal vous propose une terrasse, des...",47.224487,5.956124,7.9,630.0,EUR,"Recommandé pour votre groupe\n1×\nStudio Double\n1 lit double\n1×\nStudio Triple Standard\n2 lits (1 lit simple, 1 lit double)",-1292.1,Besançon
33,Dijon,Appart'hôtel Odalys City - Dijon Centre Les Cordeliers,https://www.booking.com/hotel/fr/appart-39-odalys-les-cordeliers.fr.html,"3/5, rue Turgot, Centre-ville de Dijon, 21000 Dijon, France, 21000 3/5, rue Turgot, France",L’Appart'hôtel Odalys City - Dijon Centre Les Cordeliers vous accueille dans le centre historique de Dijon.,47.318270,5.040115,8.1,645.0,EUR,"Recommandé pour votre groupe\nAppartement 2 Chambres (6 Adultes)\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n4 lits (2 lits simples, 1 lit double, 1 canapé-lit)\nAnnulation gratuite étendue",-1441.9,Dijon
34,Dijon,Novotel Dijon Sud,https://www.booking.com/hotel/fr/novotel-dijon-sud.fr.html,"11 Route De Beaune, 21160 Dijon, France, 21160 11 Route De Beaune, France","Situé sur la route des vins de Bourgogne, le Novotel Dijon Sud se trouve à 10 minutes de Dijon, dans la région des vignobles de Marsannay-la-Côte.",47.279527,5.007706,7.1,673.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Double Classique avec Canapé-Lit\n4 lits (2 lits doubles, 2 canapés-lits)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-1722.9,Dijon
35,Dijon,Holiday Inn Dijon Toison D'or by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon.fr.html,"1 Place Marie de Bourgogne, 21000 Dijon, France, 21000 1 Place Marie de Bourgogne, France","Doté d'un spa avec un sauna, un hammam et une salle de sport, le Holiday Inn Dijon Toison D'or vous accueille en périphérie du centre-ville historique de...",47.355700,5.052000,8.2,707.0,EUR,Recommandé pour votre groupe\n1×\nChambre 1 Lit Double Standard - Vue sur Ville\n1 lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Double Standard avec 2 Lits Doubles - Vue sur Ville\n2 lits doubles\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place,-2061.8,Dijon
36,Dijon,Holiday Inn Dijon Sud - Longvic by IHG,https://www.booking.com/hotel/fr/holiday-inn-dijon-sud-longvic-an-ihg.fr.html,"3 RUE DE BEAUREGARD, 21600 Dijon, France, 21600 3 RUE DE BEAUREGARD, France","L’établissement Holiday Inn Dijon Sud - Longvic by IHG se trouve à Dijon, à 4,5 km de ce lieu d’intérêt : Arrêt de tramway Aéroport de Dijon-Bourgogne.",47.272895,5.047662,8.8,712.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Standard Lit Queen-Size\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Lit Queen-Size Standard avec Canapé-Lit - Non-Fumeurs\n2 lits (1 canapé-lit, 1 grand lit double)\nSéjour gratuit pour 1 de vos enfants\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2111.2,Dijon
40,Eguisheim,Charmante maison 3 chambres au cœur du vignoble avec terrasse,https://www.booking.com/hotel/fr/maison-voegtlinshoffen-5-pieces-6-personnes-fr-1-722-8.fr.html,"4A rue du Schauenberg, 68420 Voegtlinshoffen, France, 68420 4A rue du Schauenberg, France",L’hébergement Charmante maison 3 chambres au cœur du vignoble avec terrasse vous accueille à respectivement 11 km et 12 km de ces lieux d’intérêt : Gare de...,48.019857,7.280921,7.7,725.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salle de bains • 1 cuisine • 105 m²\n4 lits (2 lits simples, 1 lit double, 1 grand lit double)",-2242.3,Voegtlinshoffen
30,Colmar,ibis Budget Colmar Centre Gare,https://www.booking.com/hotel/fr/ibis-budget-colmar-centre-ville.fr.html,"15 Rue Stanislas, 68000 Colmar, France, 68000 15 Rue Stanislas, France","L'ibis budget Colmar Centre Ville vous accueille à Colmar, dans le quartier du centre-ville, à 300 mètres de la Maison des Têtes et à 600 mètres de la...",48.079698,7.352362,7.2,725.0,EUR,"Recommandé pour votre groupe\n2×\nChambre Triple avec 1 Lit Double et 1 Lit Superposé\n4 lits (2 lits simples, 2 lits doubles)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-2242.8,Colmar
41,Eguisheim,Les trois pierres,https://www.booking.com/hotel/fr/les-trois-pierres-eguisheim.fr.html,"10 Rue des trois pierres, 68420 Eguisheim, France, 68420 10 Rue des trois pierres, France","L’hébergement Les trois pierres se situe à Eguisheim, à respectivement 6,1 km, 6,9 km et 7,4 km de ces lieux d’intérêt : Gare de Colmar, Maison des Têtes...",48.045389,7.301809,8.8,862.0,EUR,"Recommandé pour votre groupe\nMaison 3 Chambres\nMaison de vacances entière • 3 chambres • 1 salon • 2 salles de bains • 1 cuisine • 110 m²\n5 lits (2 lits simples, 1 canapé-lit, 2 grands lits doubles)",-3611.2,Eguisheim
4,Annecy,Ibis Annecy - Cran-Gevrier,https://www.booking.com/hotel/fr/hotel-balladins-annecy-superior.fr.html,"38, Avenue De La République, 74960 Annecy, France, 74960 38, Avenue De La République, France",L'Ibis Annecy - Cran-Gevrier se trouve à 5 minutes en voiture du centre d'Annecy et de son lac.,45.907603,6.107626,7.4,885.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Lits Jumeaux Standard\n2 lits simples\n1×\nChambre Standard avec 1 Lit Double et 1 Lit Simple\n2 lits (1 lit simple, 1 lit double)",-3842.6,Annecy
5,Annecy,Centre Jean XXIII,https://www.booking.com/hotel/fr/centre-jean-xxiii.fr.html,"Annecy-le-Vieux 10 Chemin du Bray, 74940 Annecy, France, 74940 Annecy-le-Vieux 10 Chemin du Bray, France","Doté d’une terrasse bien exposée, le Centre Jean XXIII se trouve à Annecy, à 1,8 km du lac et à 3 km de la vieille ville.",45.918323,6.152507,8.1,968.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double Standard\n1 lit double • Lit bébé gratuit toujours disponible\nPetit-déjeuner compris\n1×\nAppartement avec Balcon\nAppartement entier • 2 chambres • 1 salon • 1 salle de bains • 50 m²\n3 lits (2 lits simples, 1 lit double) • Lit bébé gratuit toujours disponible",-4671.9,Annecy
31,Colmar,"Hotel L'Europe Colmar, BW Signature Collection",https://www.booking.com/hotel/fr/l-europe.fr.html,"15 route de Neuf Brisach - Horbourg Wihr, 68180 Colmar, France, 68180 15 route de Neuf Brisach - Horbourg Wihr, France","Welcome to the Hotel & Restaurant l'Europe, located just 3 km from the pretty town of Colmar and its Petite Venise district, the Hotel Europe is your dream...",48.077206,7.403872,8.6,971.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Confort sans Accès au Spa\n1 grand lit double\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place\n1×\nChambre Familiale avec 1 Lit Queen-Size et 2 Lits Simples - Non-Fumeurs\n3 lits (2 lits simples, 1 grand lit double)\nAnnulation gratuite\nAucun prépaiement requis – Payez sur place",-4701.4,Colmar
59,Strasbourg,Les Appartements Rue des Veaux - Quartier Cathédrale,https://www.booking.com/hotel/fr/f2-quartier-cathedrale-2eme-etage.fr.html,"1 Rue des Veaux, 67000 Strasbourg, France, 67000 1 Rue des Veaux, France","L’établissement Les Appartements Rue des Veaux - Quartier Cathédrale se trouve à Strasbourg, à 400 mètres du centre et à 400 mètres de ce lieu d’intérêt :...",48.581722,7.753513,8.5,980.0,EUR,"Recommandé pour votre groupe\nAppartement 3 Chambres - 2ème Étage\nAppartement entier • 3 chambres • 1 salon • 1 salle de bains • 1 cuisine • 100 m²\n5 lits (2 canapés-lits, 3 grands lits doubles)",-4791.5,Strasbourg
60,Strasbourg,Brit Hotel Strasbourg Le Lodge,https://www.booking.com/hotel/fr/brit-le-lodge.fr.html,"10 Rue Paul Eluard, 67200 Strasbourg, France, 67200 10 Rue Paul Eluard, France","Just 3 km from Strasbourg city centre, the Brit Hotel Le Lodge welcomes you to a modern, comfortable, and friendly setting.",48.588294,7.697447,8.4,1215.0,EUR,"Recommandé pour votre groupe\n1×\nChambre Double Confort\n1 grand lit double\n1×\nChambre Familiale\n2 lits (1 canapé-lit, 1 grand lit double)",-7141.6,Strasbourg

In [6]:
from s3_utils import save_csv_to_s3, timestamped_filename, read_csv_from_s3


df = read_csv_from_s3(
        AWS_BUCKET_NAME,
        f"{AWS_BUCKET_DIR}/hotels_top20cities.csv",
        sep=",",
        encoding="utf-8",
    )
print(df.head())
# # Nom de fichier horodaté (évite d'écraser un upload précédent)
# uri = save_csv_to_s3(hotels_df, timestamped_filename("hotels"))
cities_cols = ['city_id','city','city_lat','city_lon','city_name_','city_plus']

hotels_cols = ['city','city_id','checkin_date','checkout_date','hotel_name','url_hotel','address_hotel','hotel_description',
                'lat_hotel',	'lon_hotel','score_hotel','price_hotel','currency_hotel',
                'room_description','combined_score_hotel','hotel_city']
weather_cols = ['city_id','city','checkin_date','checkout_date',
                'avg_comfort_score','temp','humidity','wind_speed_max', 
                'clear_slots', 'rain_slots',
                'rain_sum', 'selected']

df_cities2 = df[cities_cols].dropna().drop_duplicates()
df_hotels2 = df[hotels_cols].dropna().drop_duplicates()
df_weather2 = df[weather_cols].dropna().drop_duplicates()

https://nominatim.openstreetmap.org/search
                           city  avg_comfort_score checkin_date checkout_date  \
0  Chateau du Haut Koenigsbourg              0.634   2026-09-26    2026-09-30
1                        Colmar              0.602   2026-09-26    2026-09-30
2              Gorges du Verdon              0.618   2026-09-26    2026-09-30
3  Chateau du Haut Koenigsbourg              0.634   2026-09-26    2026-09-30
4  Chateau du Haut Koenigsbourg              0.634   2026-09-26    2026-09-30

   rain_sum       temp   humidity  clear_slots  rain_slots  wind_speed_max  \
0       0.0  21.944500  42.383333            4           0            2.34
1       0.0  23.697167  47.650000            4           0            2.56
2       0.0  20.409167  48.266667            5           0            4.98
3       0.0  21.944500  42.383333            4           0            2.34
4       0.0  21.944500  42.383333            4           0            2.34

   ...                                      address_hotel  \
0  ...  19 Rue de la Liberté, 67600 Kintzheim, France,...
1  ...  48 Rue du Ladhof, 68000 Colmar, France, 68000 ...
2  ...  2 Route des Salles - Aups, 04360 Moustiers-Sai...
3  ...  1 Rue de l'École, 67750 Scherwiller, France, 6...
4  ...  47 Rue du Pinot Noir, 68590 Rodern, France, 68...

                                   hotel_description  lat_hotel  lon_hotel  \
0  L’établissement Gîtes Goettelmann Didier se tr...  48.255907   7.396019
1  L’hébergement Duplex tout équipé, proche centr...  48.086071   7.367808
2  Situé à Moustiers-Sainte-Marie (Provence-Alpes...  43.828239   6.223991
3  L’hébergement L'Aubach - appartement spacieux ...  48.287064   7.418210
4  Proposant une terrasse et offrant une vue sur ...  48.225051   7.352454

   score_hotel price_hotel currency_hotel  \
0          9.2       346.0            EUR
1          9.1       482.0            EUR
2          8.1       423.0            EUR
3          7.9       414.0            EUR
4          7.7       376.0            EUR

                                    room_description              hotel_city  \
0  Recommandé pour votre groupe\nMaison 1 Chambre...               Kintzheim
1  Recommandé pour votre groupe\nAppartement 3 Ch...                  Colmar
2  Recommandé pour votre groupe\n2×\nMobile Home\...  Moustiers-Sainte-Marie
3  Recommandé pour votre groupe\nAppartement 3 Ch...             Scherwiller
4  Recommandé pour votre groupe\nAppartement 2 Ch...                  Rodern

  combined_score_hotel
0                  9.2
1                  9.1
2                  8.1
3                  7.9
4                  7.7

[5 rows x 28 columns]

In [85]:
%whos

Variable                      Type                   Data/Info
--------------------------------------------------------------
AWS_ACCESS_KEY                str                    AKIA5Q4LO2TJDK4TYAHI
AWS_BUCKET_DIR                str                    /kayak
AWS_BUCKET_NAME               str                    kayak-cyril
AWS_DB_NAME                   str                    kayak-db-cyril
AWS_DB_PASS                   str                    Siril12_kayak
AWS_DB_USER                   str                    postgres_kayak
AWS_REGION                    str                    eu-west-3
AWS_SECRET_ACCESS_KEY         str                    /Tqy2dBbI6BfriCFwyEVlgr11Vxm91z5AsN9XR8B
BASE_DIR                      WindowsPath            c:\Users\Cyril\Documents\<...>ock1\Kayak_weather_hotels
BASE_URL_NOMINATIM            str                    https://nominatim.openstreetmap.org/search
BASE_URL_OPENWEATHERMAP       str                    https://api.openweathermap.org/data/2.5
CONFIG_CITIES_FILE            str                    cities.csv
DATA_DIR                      str                    data
DATA_DIR_CONFIG               str                    data/config
DATA_DIR_CSV                  str                    data/csv
DATA_DIR_HTML                 str                    data/html
DATA_DIR_JSON                 str                    data/json
DATA_DIR_JSON_CITIES          str                    data/json/cities
DATA_DIR_JSON_HOTELS          str                    data/json/hotels
DEFAULT_PARAMS                dict                   n=1
HEADERS                       dict                   n=1
Literal                       _LiteralSpecialForm    typing.Literal
MAX_CITIES_NUMBER             int                    35
Optional                      _SpecialForm           typing.Optional
Path                          type                   <class 'pathlib.Path'>
RDSHOST                       str                    kayak-db-cyril.c96g6864en<...>-west-3.rds.amazonaws.com
SRC_DIR                       WindowsPath            c:\Users\Cyril\Documents\<...>\Kayak_weather_hotels\src
USER_AGENT                    str                    Mozilla/5.0 (X11; Linux x<...>e/124.0.0.0 Safari/537.36
Union                         _SpecialForm           typing.Union
VALID_TYPES                   set                    {'city', 'municipality', <...>ounty', 'islet', 'gorge'}
WEATHER_API_KEY               str                    e6c25cd16e57edea5d19d272bf7c6a91
add_path                      function               <function add_path at 0x000001496E7A1440>
booking_scraper_init          module                 <module 'booking_scraper_<...>booking_scraper_init.py'>
checkin_date                  str                    2026-09-26
checkout_date                 str                    2026-09-29
cities_bis                    DataFrame              Shape: (37, 6)
cities_cols                   list                   n=6
cities_list_df                DataFrame              Shape: (37, 3)
cities_top20_hotels_2         DataFrame              Shape: (65, 21)
city_id                       function               <function city_id at 0x000001490A1B89A0>
city_uuid                     function               <function city_uuid at 0x000001490A1B8B80>
clean_cities_names            function               <function clean_cities_na<...>es at 0x000001490A17BF60>
clean_name                    function               <function clean_name at 0x000001490A17BCE0>
collect_cities_hotels         function               <function collect_cities_<...>ls at 0x0000014911162E80>
compile_weather               function               <function compile_weather at 0x000001490A1D2660>
compile_weather2              function               <function compile_weather2 at 0x000001490A1D2980>
config_cities_list            list                   n=35
date_heure_today              str                    2026-09-25 10:27:06
date_span                     ndarray                5: 5 elems, type `object`, 40 bytes
de                            module                 <module 'django.conf.loca<...>locale\\de\\__init__.py'>
df_cities                     DataFrame              Shape: (37, 6)
df_weather2                   DataFrame              Shape: (40, 25)
engine                        Engine                 Engine(postgresql+psycopg<...>.com:5432/kayak-db-cyril)
extract_all_coordinates       function               <function extract_all_coo<...>es at 0x000001490A17A7A0>
extract_city                  function               <function extract_city at 0x00000149114EADE0>
extract_coordinates           function               <function extract_coordin<...>es at 0x000001490A17A5C0>
fig                           Figure                 Figure({\n    'data': [{'<...>        'width': 900}\n})
get_coordinates_cities        function               <function get_coordinates<...>es at 0x000001490A1BB420>
get_hotel_availability        function               <function get_hotel_avail<...>ty at 0x0000014910A52480>
get_hotel_availability_sync   function               <function get_hotel_avail<...>nc at 0x000001490F3E80E0>
get_nominatim                 function               <function get_nominatim at 0x000001490A179E40>
get_rds_engine                function               <function get_rds_engine at 0x0000014913EAE8E0>
get_weather                   function               <function get_weather at 0x000001490A1D25C0>
get_weather_data_for_cities   function               <function get_weather_dat<...>es at 0x000001490A1D28E0>
glob                          module                 <module 'glob' from 'C:\\<...>Python311\\Lib\\glob.py'>
hotels_bis                    DataFrame              Shape: (35, 13)
hotels_cols                   list                   n=13
hotels_df                     DataFrame              Shape: (35, 12)
importlib                     module                 <module 'importlib' from <...>\importlib\\__init__.py'>
json                          module                 <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
lat                           float64                48.649518
load_cities                   function               <function load_cities at 0x000001490A179F80>
load_dotenv                   function               <function load_dotenv at 0x000001496E6AA5C0>
load_from_cache               function               <function load_from_cache at 0x000001490A17BE20>
logger                        Logger                 <Logger __main__ (INFO)>
logging                       module                 <module 'logging' from 'C<...>b\\logging\\__init__.py'>
lon                           float64                -2.0260409
max_results                   int                    5
n_adults                      int                    2
n_children                    int                    3
n_rooms                       int                    2
notebook_dir                  WindowsPath            c:\Users\Cyril\Documents\<...>ock1\Kayak_weather_hotels
os                            module                 <module 'os' (frozen)>
pd                            module                 <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
plus_name                     function               <function plus_name at 0x000001490A17A8E0>
px                            module                 <module 'plotly.express' <...>y\\express\\__init__.py'>
random                        module                 <module 'random' from 'C:<...>thon311\\Lib\\random.py'>
re                            module                 <module 're' from 'C:\\Pr<...>1\\Lib\\re\\__init__.py'>
read_csv_from_s3              function               <function read_csv_from_s3 at 0x0000014914800EA0>
requests                      module                 <module 'requests' from '<...>\\requests\\__init__.py'>
result_weather                DataFrame              Shape: (185, 14)
results1                      Series                 Shape: (6,)
results_df                    DataFrame              Shape: (37, 6)
save_city_hotel               function               <function save_city_hotel at 0x000001490F3E8FE0>
save_csv_to_s3                function               <function save_csv_to_s3 at 0x0000014914121120>
save_df_to_rds                function               <function save_df_to_rds at 0x0000014911146F20>
save_to_cache                 function               <function save_to_cache at 0x000001490A17A980>
select_best_weather_cities    function               <function select_best_wea<...>es at 0x000001496E4FAFC0>
select_top_hotels             function               <function select_top_hote<...>ls at 0x000001490F3E8EA0>
slugify                       function               <function slugify at 0x000001490A1B8AE0>
summarize_weather             function               <function summarize_weath<...>er at 0x000001490A1D3560>
sys                           module                 <module 'sys' (built-in)>
time                          module                 <module 'time' (built-in)>
timestamped_filename          function               <function timestamped_fil<...>me at 0x0000014914121080>
top20_combined                DataFrame              Shape: (35, 12)
top20_hotels_combined         DataFrame              Shape: (35, 13)
top_cities                    DataFrame              Shape: (37, 6)
top_cities2                   DataFrame              Shape: (37, 9)
unicodedata                   module                 <module 'unicodedata' fro<...>\\DLLs\\unicodedata.pyd'>
uuid                          module                 <module 'uuid' from 'C:\\<...>Python311\\Lib\\uuid.py'>
warnings                      module                 <module 'warnings' from '<...>on311\\Lib\\warnings.py'>
weather_forecast              dict                   n=5

In [8]:
import os
from rds_utils import get_rds_engine, save_df_to_rds

engine = get_rds_engine(
    host= RDSHOST,       # ex: mydb.xxxxx.eu-west-3.rds.amazonaws.com
    database= AWS_DB_NAME,
    user = AWS_DB_USER,
    password= AWS_DB_PASS,
    port= 5432,
    driver= "postgresql+psycopg2",
)
save_df_to_rds(df_cities2, "cities", engine, if_exists="replace")
save_df_to_rds(df_hotels2, "hotels", engine, if_exists="replace")
save_df_to_rds(df_weather2, "weather", engine, if_exists="replace")

RuntimeError: Échec de l'écriture dans 'cities' : (psycopg2.OperationalError) connection to server at "kayak-db-cyril.c96g6864enod.eu-west-3.rds.amazonaws.com" (172.31.40.79), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)